"""
app/services/recommendation_service.py
-----------------------------------------
Turns the numbers from forecasting_service.py -- PLUS the SME's own
input business parameters (industry and sub-category, what they sell,
what makes them different, an optional price list, startup capital,
employee count, business stage) compared against the real businesses
already on file for that industry/location (seeded market_data and/or
live Google Places API results) -- into the structured recommendation
the capstone paper's storyboard calls for: a headline, an opportunity
type, a one-sentence summary, a "Why This Works" reasons list, and a
"Considerations" risks list (see app/templates/sme/recommendations.html
and Reference/Figma_Storyboard's recommendations page).

The real schema has only ONE text column for this
(forecast_result.recommendation TEXT -- no separate reasons_json /
risks_json columns), so this module JSON-serializes the structured
dict into that single column (serialize_recommendation) and parses it
back out again (parse_recommendation) -- including a best-effort parse
of the OLD plain-text format this project used before this change, so
rows generated by an earlier version of the app still render correctly
instead of showing raw text or breaking the page.

Two modes, controlled by the use_llm_recommendations system setting
(Admin > System Settings, or USE_LLM_RECOMMENDATIONS in .env):

  - RULE-BASED (default, no API key needed): a deterministic dict
    built from the actual scores + the SME's own inputs. Free,
    offline, instant, and 100% reproducible -- good for a thesis
    defense where you need to explain exactly why the system said
    what it said.

  - LLM-ASSISTED (opt-in): calls app/services/llm_service.py (GPT via
    OpenAI/OpenRouter, or Claude via Anthropic -- see LLM_PROVIDER in
    .env) to turn the SAME grounded numbers into a more naturally
    worded, GPT-written version of the same structured shape. If that
    call fails for any reason (no key, no internet, quota, malformed
    JSON back), this silently falls back to the rule-based dict above
    -- the page never breaks because of this.
"""

import json
import re

from app.models import SystemSetting

# Every recommendation dict -- rule-based, LLM-generated, or parsed back
# out of storage -- has exactly these keys, so every template that
# reads one (recommendations.html, home.html) can rely on the shape
# without checking for missing pieces.
_KEYS = ("headline", "opportunity_type", "summary", "reasons", "risks", "generated_by",
         "subcategory_analysis", "innovation")


# ---------------------------------------------------------------------
# 1. Context building -- gathers the SME's OWN input parameters and the
#    real comparison data (competitor sample, population) into the one
#    dict both the rule-based generator and the LLM prompt read from.
# ---------------------------------------------------------------------

def price_summary(items):
    """{count, priced, low, high} for the optional price list, or None.
    Only the owner's own figures -- no market price benchmark is
    invented to compare them against."""
    items = [i for i in (items or []) if isinstance(i, dict) and i.get("item")]
    if not items:
        return None
    prices = [float(i["price"]) for i in items if i.get("price") is not None]
    return {
        "count": len(items),
        "priced": len(prices),
        "low": min(prices) if prices else None,
        "high": max(prices) if prices else None,
    }


def build_recommendation_context(sme_profile, scores, competitor_sample=None, competitor_simulated=True,
                                  population=0, subcategory_analysis=None):
    """`sme_profile` is the SME's own SmeProfile row (their input
    business parameters). `scores` is the dict compute_scores() in
    forecasting_service.py just returned for that same profile -- after
    the sub-category adjustment, when there is one (see
    subcategory_service.adjusted_scores), in which case it also carries
    industry_saturation_index for the comparison.
    `competitor_sample` is a short list of real (or simulated,
    clearly flagged) business names on file for this industry+location
    -- see forecasting_service.generate_forecast_for_profile().
    `subcategory_analysis` is subcategory_service.direct_competition()'s
    result, or None when the plan has no sub-category.

    Monthly revenue is deliberately absent: it is no longer collected
    (see app/services/plan_params.py)."""
    offering_items = list(getattr(sme_profile, "offering_items", None) or [])
    return {
        "business_name": sme_profile.business_name,
        "industry_type": sme_profile.industry_type,
        "subcategory": getattr(sme_profile, "subcategory", None),
        "subcategory_label": getattr(sme_profile, "subcategory_label", None),
        "product_offering": getattr(sme_profile, "product_offering", None) or "",
        "innovation_idea": getattr(sme_profile, "innovation_idea", None) or "",
        "offering_items": offering_items,
        "price_summary": price_summary(offering_items),
        "location": sme_profile.location,
        "business_stage": sme_profile.business_stage,
        "years_in_operation": sme_profile.years_in_operation(),
        "startup_capital": float(sme_profile.startup_capital or 0),
        "employee_count": sme_profile.employee_count or 0,
        "saturation_index": scores["saturation_index"],
        "industry_saturation_index": scores.get("industry_saturation_index", scores["saturation_index"]),
        "cluster_label": scores["cluster_label"],
        "viability_score": scores["viability_score"],
        "confidence_level": scores["confidence_level"],
        "population": int(population or 0),
        "competitor_count": scores["competitor_count"],
        "competitor_simulated": competitor_simulated,
        "competitor_sample": competitor_sample or [],
        "subcategory_analysis": subcategory_analysis,
    }


# ---------------------------------------------------------------------
# 2. Rule-based generator -- always available, no API key needed. This
#    is also what every LLM call ultimately falls back to.
# ---------------------------------------------------------------------

def _headline_and_type_for(cluster_label):
    if cluster_label == "Saturated":
        return ("HIGH SATURATION -- avoid this market or pivot to a clearly differentiated niche.",
                "High Saturation")
    if cluster_label == "High":
        return ("MODERATE-HIGH SATURATION -- consider a niche angle or a nearby underserved location.",
                "Moderate Opportunity")
    if cluster_label == "Moderate":
        return ("MODERATE OPPORTUNITY -- viable with a solid differentiation strategy.",
                "Moderate Opportunity")
    return ("HIGH OPPORTUNITY -- favorable conditions for market entry.", "High Opportunity")


def _kind_of_business(context):
    """"a bakery" when a sub-category is known, else "a food and beverage
    business" -- the summary should name what the owner actually said
    they are opening."""
    label = context.get("subcategory_label")
    if context.get("subcategory") and context.get("subcategory") != "other" and label:
        return label.lower()
    return f"{context['industry_type'].lower()} business"


def _summary_for(context):
    summary = (
        f"A {_kind_of_business(context)} in {context['location']} is currently classified as "
        f"'{context['cluster_label']}' saturation ({round(context['saturation_index'])}%), with a viability "
        f"score of {context['viability_score']}/10 for the parameters you entered."
    )
    analysis = context.get("subcategory_analysis")
    if analysis and analysis.get("adjusts_score"):
        summary += (
            f" Industry-wide the figure is {round(context['industry_saturation_index'])}%; it moves because "
            f"direct {analysis['label'].lower()} competition here is "
            f"{'lighter' if analysis['density_ratio'] < 1 else 'heavier'} than usual."
        )
    return summary


def _reasons_for(context):
    cluster_label = context["cluster_label"]
    industry_lower = context["industry_type"].lower()
    reasons = []
    if cluster_label in ("Low", "Moderate"):
        reasons.append(f"only {context['competitor_count']} existing {industry_lower} business(es) found "
                        f"in {context['location']}")
        if context["population"]:
            reasons.append(f"a real population of {context['population']:,} gives room for a new entrant")
        else:
            reasons.append("demand indicators suggest room for a new entrant")
    else:
        reasons.append(f"{context['competitor_count']} existing {industry_lower} business(es) already "
                        f"serve {context['location']}")
    analysis = context.get("subcategory_analysis")
    if analysis and not analysis.get("is_estimated") and analysis.get("density_ratio", 1) < 1:
        reasons.append(
            f"only {analysis['direct_count']} direct {analysis['label'].lower()} competitor(s) measured in "
            f"{context['location']} -- fewer than its {analysis['industry_count']} "
            f"{industry_lower} businesses would normally hold"
        )
    if context["startup_capital"]:
        reasons.append(f"your planned capital of PHP {context['startup_capital']:,.0f} is on file for this plan")
    reasons.append(f"model confidence for this estimate is {round(context['confidence_level'])}%")
    return reasons


def _risks_for(context):
    cluster_label = context["cluster_label"]
    risks = []
    if cluster_label in ("High", "Saturated"):
        risks.append(f"the market is already {round(context['saturation_index'])}% saturated in "
                      f"{context['location']}")
        risks.append("expect strong price/brand competition from existing businesses")
    else:
        risks.append("initial brand-awareness building will still be required")
        risks.append("monitor seasonal demand fluctuations after launch")
    analysis = context.get("subcategory_analysis")
    if analysis:
        if analysis.get("is_estimated"):
            risks.append(
                f"the direct {analysis['label'].lower()} competitor count (~{analysis['direct_count']}) is an "
                f"estimate -- no sub-category count is on file for {context['location']} yet, so the score "
                f"is the industry-wide one"
            )
        elif analysis.get("density_ratio", 1) > 1:
            risks.append(
                f"{analysis['direct_count']} direct {analysis['label'].lower()} competitor(s) in "
                f"{context['location']} -- denser than usual for its {analysis['industry_count']} "
                f"{context['industry_type'].lower()} businesses"
            )
    if context["competitor_simulated"]:
        risks.append("competitor count for this area is a simulated estimate -- connect a live Google "
                      "Places API key for exact figures")
    return risks


# How much a new entrant has to stand out, by the saturation tier the
# model put this plan in. Read from the model's own output -- the only
# market fact the rule-based writer has -- not from the idea's wording,
# which it cannot judge. Judging the idea itself is the LLM's job.
_DIFFERENTIATION_NEED = {
    "Saturated": "Very high",
    "High": "High",
    "Moderate": "Moderate",
    "Low": "Low",
}

_DIFFERENTIATION_SUGGESTIONS = {
    "Very high": [
        "make the difference visible before anyone buys -- signage, packaging or a sample customers can try",
        "test the idea with a small batch or a weekend stall before committing the full capital",
        "pick one thing to be known for rather than competing on everything the established shops offer",
    ],
    "High": [
        "lead with the difference in your name, signage and first posts, so it is what people remember",
        "price the new item so trying it is an easy yes next to what regulars already buy",
        "ask your first customers what made them choose you, and double down on that",
    ],
    "Moderate": [
        "the market has room, so the idea is a head start rather than a lifeline -- consistency matters as much",
        "keep the idea simple enough to deliver the same way every day",
    ],
    "Low": [
        "competition is light, so reliability and convenience can matter more than novelty at first",
        "keep the idea as a way to hold customers once competitors arrive",
    ],
}


def _rule_based_innovation(context):
    """What the plan's differentiation is up against. The rule-based
    writer does NOT rate how new the idea is -- it has no way to know --
    so `novelty` stays None here and only the LLM fills it in."""
    need = _DIFFERENTIATION_NEED.get(context["cluster_label"], "Moderate")
    analysis = context.get("subcategory_analysis")
    if analysis:
        rivals = f"{'about ' if analysis.get('is_estimated') else ''}{analysis['direct_count']} direct " \
                 f"{analysis['label'].lower()} competitor(s)"
    else:
        rivals = f"{context['competitor_count']} {context['industry_type'].lower()} business(es)"

    idea = (context.get("innovation_idea") or "").strip()
    if idea:
        summary = (
            f"Your idea goes up against {rivals} in {context['location']}, where the market is "
            f"{round(context['saturation_index'])}% saturated -- differentiation need: {need.lower()}."
        )
    else:
        summary = (
            f"You have not said what makes the business different yet. With {rivals} in "
            f"{context['location']}, differentiation need is {need.lower()} -- add your idea to the plan "
            f"for a clearer read."
        )

    prices = context.get("price_summary")
    if prices and prices.get("priced"):
        if prices["low"] == prices["high"]:
            summary += f" Your price list has {prices['count']} item(s) at PHP {prices['low']:,.2f}."
        else:
            summary += (f" Your price list has {prices['count']} item(s), from PHP {prices['low']:,.2f} "
                        f"to PHP {prices['high']:,.2f}.")

    return {
        "has_idea": bool(idea),
        "differentiation_need": need,
        "novelty": None,
        "summary": summary,
        "suggestions": list(_DIFFERENTIATION_SUGGESTIONS.get(need, [])),
        "generated_by": "rule_based",
    }


def _rule_based_recommendation(context):
    headline, opportunity_type = _headline_and_type_for(context["cluster_label"])
    return {
        "headline": headline,
        "opportunity_type": opportunity_type,
        "summary": _summary_for(context),
        "reasons": _reasons_for(context),
        "risks": _risks_for(context),
        "generated_by": "rule_based",
        "subcategory_analysis": context.get("subcategory_analysis"),
        "innovation": _rule_based_innovation(context),
    }


def llm_recommendations_enabled():
    """The ONE place that decides whether the LLM is asked to write.

    There used to be two answers to this question and only one of them
    was ever consulted. USE_LLM_RECOMMENDATIONS is documented in .env,
    in DEPLOYMENT.md and in render.yaml as the switch -- and it was
    read into Config and then never looked at. The real switch was a
    row in the system_settings table, reachable only through Admin >
    System Settings. Setting the environment variable on a host and
    watching nothing change is a genuinely baffling half hour, so:

      * If USE_LLM_RECOMMENDATIONS is set in the environment, it wins.
        An operator who has written the variable down in a deployment
        panel means it, and they may have no way to reach the admin UI
        on a fresh instance.
      * Otherwise the database setting decides, so the admin toggle
        keeps working exactly as before for anyone not setting the
        variable.

    Being explicit matters here: an UNSET variable must fall through to
    the database, while USE_LLM_RECOMMENDATIONS=false must actually
    turn the feature off rather than being indistinguishable from
    absent.
    """
    import os

    raw = os.environ.get("USE_LLM_RECOMMENDATIONS")
    if raw is not None and str(raw).strip() != "":
        return str(raw).strip().lower() in ("1", "true", "yes", "on")

    return SystemSetting.get_bool("use_llm_recommendations", False)


def build_recommendation(context):
    """Returns a structured recommendation dict -- {headline,
    opportunity_type, summary, reasons, risks, generated_by} -- ready
    for serialize_recommendation() to store in
    forecast_result.recommendation.

    Tries the configured LLM (GPT-4o-mini via OpenRouter, or Claude --
    see LLM_PROVIDER / OPENAI_BASE_URL in .env) when
    use_llm_recommendations is on; always falls back to the
    deterministic rule-based recommendation above if the LLM is off,
    unconfigured, or fails for any reason -- the page never breaks
    because of this."""
    recommendation = _rule_based_recommendation(context)

    if llm_recommendations_enabled():
        from app.services.llm_service import generate_recommendation_json

        llm_payload = generate_recommendation_json(context)
        if llm_payload:
            rule_innovation = recommendation["innovation"]
            llm_payload = dict(llm_payload)
            llm_innovation = llm_payload.pop("innovation", None)
            recommendation = dict(llm_payload)
            # The sub-category figures are measurements, never the
            # model's words -- they always come from the context.
            recommendation["subcategory_analysis"] = context.get("subcategory_analysis")
            if llm_innovation and rule_innovation.get("has_idea"):
                # The LLM judges the idea; the differentiation need stays
                # the one read from the saturation model.
                recommendation["innovation"] = {
                    **rule_innovation,
                    "novelty": llm_innovation["novelty"],
                    "summary": llm_innovation["summary"] or rule_innovation["summary"],
                    "suggestions": llm_innovation["suggestions"] or rule_innovation["suggestions"],
                    "generated_by": llm_payload.get("generated_by"),
                }
            else:
                recommendation["innovation"] = rule_innovation

    return recommendation


# ---------------------------------------------------------------------
# 3. Storage -- JSON-in-a-TEXT-column, with backward-compatible parsing
#    for rows written before this change existed.
# ---------------------------------------------------------------------

def serialize_recommendation(recommendation):
    """Ready to store directly in forecast_result.recommendation."""
    return json.dumps(
        {key: recommendation.get(key) for key in _KEYS},
        ensure_ascii=False,
    )


def _empty_recommendation():
    return {
        "headline": "",
        "opportunity_type": "Moderate Opportunity",
        "summary": "No recommendation available yet.",
        "reasons": [],
        "risks": [],
        "generated_by": "none",
        "subcategory_analysis": None,
        "innovation": None,
    }


def _opportunity_type_from_headline(headline):
    upper = (headline or "").upper()
    if "HIGH SATURATION" in upper:
        return "High Saturation"
    if "MODERATE" in upper:
        return "Moderate Opportunity"
    if "HIGH OPPORTUNITY" in upper:
        return "High Opportunity"
    return "Moderate Opportunity"


def parse_recommendation(raw_text):
    """Returns the structured dict every template expects, whether
    `raw_text` is one of THIS version's JSON-serialized
    recommendations, or a legacy plain-text row written by the old
    rule_based_text()/LLM plain-text generator this module used before
    this change (format: "<HEADLINE>\\n\\n<summary>\\n\\nWhy: r1; r2.
    \\n\\nConsiderations: c1; c2."). Never raises -- a value nobody can
    make sense of still returns a fully-shaped dict so every template
    field always has *something* to render."""
    if not raw_text or not str(raw_text).strip():
        return _empty_recommendation()

    text = str(raw_text).strip()

    if text.startswith("{"):
        try:
            payload = json.loads(text)
        except (ValueError, TypeError):
            payload = None
        if isinstance(payload, dict) and "headline" in payload:
            return {
                "headline": payload.get("headline") or "",
                "opportunity_type": payload.get("opportunity_type") or "Moderate Opportunity",
                "summary": payload.get("summary") or "",
                "reasons": [str(r) for r in (payload.get("reasons") or [])],
                "risks": [str(r) for r in (payload.get("risks") or [])],
                "generated_by": payload.get("generated_by") or "rule_based",
                # Absent on forecasts written before sub-categories and
                # the innovation read existed; templates check for None.
                "subcategory_analysis": payload.get("subcategory_analysis")
                if isinstance(payload.get("subcategory_analysis"), dict) else None,
                "innovation": payload.get("innovation")
                if isinstance(payload.get("innovation"), dict) else None,
            }

    # Legacy plain-text fallback (pre-JSON format).
    headline = text.split("\n", 1)[0].strip()

    summary_match = re.search(r"\n\n(.*?)\n\nWhy:", text, re.DOTALL)
    summary = re.sub(r"\s+", " ", summary_match.group(1)).strip() if summary_match else ""

    why_match = re.search(r"Why:\s*(.*?)\.?\s*(?:\n\n|$)", text, re.DOTALL)
    reasons = [r.strip() for r in why_match.group(1).split(";") if r.strip()] if why_match else []

    considerations_match = re.search(r"Considerations:\s*(.*?)\.?\s*$", text, re.DOTALL)
    risks = [r.strip() for r in considerations_match.group(1).split(";") if r.strip()] if considerations_match else []

    return {
        "headline": headline,
        "opportunity_type": _opportunity_type_from_headline(headline),
        "summary": summary,
        "reasons": reasons,
        "risks": risks,
        "generated_by": "legacy",
        "subcategory_analysis": None,
        "innovation": None,
    }


# ---------------------------------------------------------------------
# 4. Small display-only helpers for the Recommendations page -- derived
#    from real numbers already on file, never fabricated ranges.
# ---------------------------------------------------------------------

def competition_level_label(competitor_count):
    count = int(competitor_count or 0)
    if count == 0:
        return f"Very Low ({count} competitors)"
    if count <= 2:
        return f"Low ({count} competitors)"
    if count <= 6:
        return f"Moderate ({count} competitors)"
    return f"High ({count} competitors)"
