"""
app/services/recommendation_service.py
-----------------------------------------
Turns the numbers from forecasting_service.py -- PLUS the SME's own
input business parameters (startup capital, employee count, business
stage, monthly revenue estimate) compared against the real businesses
already on file for that industry/location (seeded market_data and/or
live Google Places API results) -- into the structured recommendation
the capstone paper's storyboard calls for: a headline, an opportunity
type, a one-sentence summary, a "Why This Works" reasons list, and a
"Considerations" risks list (see app/templates/sme/recommendations.html
and Reference/Figma_Storyboard's recommendations page).

The real schema has only ONE text column for this
(forecast_result.recommendation TEXT -- no separate reasons_json /
risks_json columns), so this module JSON-serializes the structured
dict into that single column (serialize_recommendation) and parses it
back out again (parse_recommendation) -- including a best-effort parse
of the OLD plain-text format this project used before this change, so
rows generated by an earlier version of the app still render correctly
instead of showing raw text or breaking the page.

Two modes, controlled by the use_llm_recommendations system setting
(Admin > System Settings, or USE_LLM_RECOMMENDATIONS in .env):

  - RULE-BASED (default, no API key needed): a deterministic dict
    built from the actual scores + the SME's own inputs. Free,
    offline, instant, and 100% reproducible -- good for a thesis
    defense where you need to explain exactly why the system said
    what it said.

  - LLM-ASSISTED (opt-in): calls app/services/llm_service.py (GPT via
    OpenAI/OpenRouter, or Claude via Anthropic -- see LLM_PROVIDER in
    .env) to turn the SAME grounded numbers into a more naturally
    worded, GPT-written version of the same structured shape. If that
    call fails for any reason (no key, no internet, quota, malformed
    JSON back), this silently falls back to the rule-based dict above
    -- the page never breaks because of this.
"""

import json
import re

from app.models import SystemSetting

# Every recommendation dict -- rule-based, LLM-generated, or parsed back
# out of storage -- has exactly these keys, so every template that
# reads one (recommendations.html, home.html) can rely on the shape
# without checking for missing pieces.
_KEYS = ("headline", "opportunity_type", "summary", "reasons", "risks", "generated_by")


# ---------------------------------------------------------------------
# 1. Context building -- gathers the SME's OWN input parameters and the
#    real comparison data (competitor sample, population) into the one
#    dict both the rule-based generator and the LLM prompt read from.
# ---------------------------------------------------------------------

def build_recommendation_context(sme_profile, scores, competitor_sample=None, competitor_simulated=True,
                                  population=0):
    """`sme_profile` is the SME's own SmeProfile row (their input
    business parameters). `scores` is the dict compute_scores() in
    forecasting_service.py just returned for that same profile.
    `competitor_sample` is a short list of real (or simulated,
    clearly flagged) business names on file for this industry+location
    -- see forecasting_service.generate_forecast_for_profile()."""
    return {
        "business_name": sme_profile.business_name,
        "industry_type": sme_profile.industry_type,
        "location": sme_profile.location,
        "business_stage": sme_profile.business_stage,
        "years_in_operation": sme_profile.years_in_operation(),
        "startup_capital": float(sme_profile.startup_capital or 0),
        "employee_count": sme_profile.employee_count or 0,
        "monthly_revenue_est": float(sme_profile.monthly_revenue_est or 0),
        "saturation_index": scores["saturation_index"],
        "cluster_label": scores["cluster_label"],
        "viability_score": scores["viability_score"],
        "confidence_level": scores["confidence_level"],
        "population": int(population or 0),
        "competitor_count": scores["competitor_count"],
        "competitor_simulated": competitor_simulated,
        "competitor_sample": competitor_sample or [],
    }


# ---------------------------------------------------------------------
# 2. Rule-based generator -- always available, no API key needed. This
#    is also what every LLM call ultimately falls back to.
# ---------------------------------------------------------------------

def _headline_and_type_for(cluster_label):
    if cluster_label == "Saturated":
        return ("HIGH SATURATION -- avoid this market or pivot to a clearly differentiated niche.",
                "High Saturation")
    if cluster_label == "High":
        return ("MODERATE-HIGH SATURATION -- consider a niche angle or a nearby underserved location.",
                "Moderate Opportunity")
    if cluster_label == "Moderate":
        return ("MODERATE OPPORTUNITY -- viable with a solid differentiation strategy.",
                "Moderate Opportunity")
    return ("HIGH OPPORTUNITY -- favorable conditions for market entry.", "High Opportunity")


def _summary_for(context):
    return (
        f"A {context['industry_type'].lower()} business in {context['location']} is currently classified as "
        f"'{context['cluster_label']}' saturation ({round(context['saturation_index'])}%), with a viability "
        f"score of {context['viability_score']}/10 for the parameters you entered."
    )


def _reasons_for(context):
    cluster_label = context["cluster_label"]
    industry_lower = context["industry_type"].lower()
    reasons = []
    if cluster_label in ("Low", "Moderate"):
        reasons.append(f"only {context['competitor_count']} existing {industry_lower} business(es) found "
                        f"in {context['location']}")
        if context["population"]:
            reasons.append(f"a real population of {context['population']:,} gives room for a new entrant")
        else:
            reasons.append("demand indicators suggest room for a new entrant")
    else:
        reasons.append(f"{context['competitor_count']} existing {industry_lower} business(es) already "
                        f"serve {context['location']}")
    if context["startup_capital"]:
        reasons.append(f"your planned capital of PHP {context['startup_capital']:,.0f} is on file for this plan")
    reasons.append(f"model confidence for this estimate is {round(context['confidence_level'])}%")
    return reasons


def _risks_for(context):
    cluster_label = context["cluster_label"]
    risks = []
    if cluster_label in ("High", "Saturated"):
        risks.append(f"the market is already {round(context['saturation_index'])}% saturated in "
                      f"{context['location']}")
        risks.append("expect strong price/brand competition from existing businesses")
    else:
        risks.append("initial brand-awareness building will still be required")
        risks.append("monitor seasonal demand fluctuations after launch")
    if context["competitor_simulated"]:
        risks.append("competitor count for this area is a simulated estimate -- connect a live Google "
                      "Places API key for exact figures")
    return risks


def _rule_based_recommendation(context):
    headline, opportunity_type = _headline_and_type_for(context["cluster_label"])
    return {
        "headline": headline,
        "opportunity_type": opportunity_type,
        "summary": _summary_for(context),
        "reasons": _reasons_for(context),
        "risks": _risks_for(context),
        "generated_by": "rule_based",
    }


def llm_recommendations_enabled():
    """The ONE place that decides whether the LLM is asked to write.

    There used to be two answers to this question and only one of them
    was ever consulted. USE_LLM_RECOMMENDATIONS is documented in .env,
    in DEPLOYMENT.md and in render.yaml as the switch -- and it was
    read into Config and then never looked at. The real switch was a
    row in the system_settings table, reachable only through Admin >
    System Settings. Setting the environment variable on a host and
    watching nothing change is a genuinely baffling half hour, so:

      * If USE_LLM_RECOMMENDATIONS is set in the environment, it wins.
        An operator who has written the variable down in a deployment
        panel means it, and they may have no way to reach the admin UI
        on a fresh instance.
      * Otherwise the database setting decides, so the admin toggle
        keeps working exactly as before for anyone not setting the
        variable.

    Being explicit matters here: an UNSET variable must fall through to
    the database, while USE_LLM_RECOMMENDATIONS=false must actually
    turn the feature off rather than being indistinguishable from
    absent.
    """
    import os

    raw = os.environ.get("USE_LLM_RECOMMENDATIONS")
    if raw is not None and str(raw).strip() != "":
        return str(raw).strip().lower() in ("1", "true", "yes", "on")

    return SystemSetting.get_bool("use_llm_recommendations", False)


def build_recommendation(context):
    """Returns a structured recommendation dict -- {headline,
    opportunity_type, summary, reasons, risks, generated_by} -- ready
    for serialize_recommendation() to store in
    forecast_result.recommendation.

    Tries the configured LLM (GPT-4o-mini via OpenRouter, or Claude --
    see LLM_PROVIDER / OPENAI_BASE_URL in .env) when
    use_llm_recommendations is on; always falls back to the
    deterministic rule-based recommendation above if the LLM is off,
    unconfigured, or fails for any reason -- the page never breaks
    because of this."""
    recommendation = _rule_based_recommendation(context)

    if llm_recommendations_enabled():
        from app.services.llm_service import generate_recommendation_json

        llm_payload = generate_recommendation_json(context)
        if llm_payload:
            recommendation = llm_payload

    return recommendation


# ---------------------------------------------------------------------
# 3. Storage -- JSON-in-a-TEXT-column, with backward-compatible parsing
#    for rows written before this change existed.
# ---------------------------------------------------------------------

def serialize_recommendation(recommendation):
    """Ready to store directly in forecast_result.recommendation."""
    return json.dumps(
        {key: recommendation.get(key) for key in _KEYS},
        ensure_ascii=False,
    )


def _empty_recommendation():
    return {
        "headline": "",
        "opportunity_type": "Moderate Opportunity",
        "summary": "No recommendation available yet.",
        "reasons": [],
        "risks": [],
        "generated_by": "none",
    }


def _opportunity_type_from_headline(headline):
    upper = (headline or "").upper()
    if "HIGH SATURATION" in upper:
        return "High Saturation"
    if "MODERATE" in upper:
        return "Moderate Opportunity"
    if "HIGH OPPORTUNITY" in upper:
        return "High Opportunity"
    return "Moderate Opportunity"


def parse_recommendation(raw_text):
    """Returns the structured dict every template expects, whether
    `raw_text` is one of THIS version's JSON-serialized
    recommendations, or a legacy plain-text row written by the old
    rule_based_text()/LLM plain-text generator this module used before
    this change (format: "<HEADLINE>\\n\\n<summary>\\n\\nWhy: r1; r2.
    \\n\\nConsiderations: c1; c2."). Never raises -- a value nobody can
    make sense of still returns a fully-shaped dict so every template
    field always has *something* to render."""
    if not raw_text or not str(raw_text).strip():
        return _empty_recommendation()

    text = str(raw_text).strip()

    if text.startswith("{"):
        try:
            payload = json.loads(text)
        except (ValueError, TypeError):
            payload = None
        if isinstance(payload, dict) and "headline" in payload:
            return {
                "headline": payload.get("headline") or "",
                "opportunity_type": payload.get("opportunity_type") or "Moderate Opportunity",
                "summary": payload.get("summary") or "",
                "reasons": [str(r) for r in (payload.get("reasons") or [])],
                "risks": [str(r) for r in (payload.get("risks") or [])],
                "generated_by": payload.get("generated_by") or "rule_based",
            }

    # Legacy plain-text fallback (pre-JSON format).
    headline = text.split("\n", 1)[0].strip()

    summary_match = re.search(r"\n\n(.*?)\n\nWhy:", text, re.DOTALL)
    summary = re.sub(r"\s+", " ", summary_match.group(1)).strip() if summary_match else ""

    why_match = re.search(r"Why:\s*(.*?)\.?\s*(?:\n\n|$)", text, re.DOTALL)
    reasons = [r.strip() for r in why_match.group(1).split(";") if r.strip()] if why_match else []

    considerations_match = re.search(r"Considerations:\s*(.*?)\.?\s*$", text, re.DOTALL)
    risks = [r.strip() for r in considerations_match.group(1).split(";") if r.strip()] if considerations_match else []

    return {
        "headline": headline,
        "opportunity_type": _opportunity_type_from_headline(headline),
        "summary": summary,
        "reasons": reasons,
        "risks": risks,
        "generated_by": "legacy",
    }


# ---------------------------------------------------------------------
# 4. Small display-only helpers for the Recommendations page -- derived
#    from real numbers already on file, never fabricated ranges.
# ---------------------------------------------------------------------

def competition_level_label(competitor_count):
    count = int(competitor_count or 0)
    if count == 0:
        return f"Very Low ({count} competitors)"
    if count <= 2:
        return f"Low ({count} competitors)"
    if count <= 6:
        return f"Moderate ({count} competitors)"
    return f"High ({count} competitors)"


def estimate_breakeven_months(startup_capital, monthly_revenue_est):
    """A simple capital / monthly-revenue estimate -- None when either
    figure is missing, so the template can say "add a revenue
    estimate" instead of showing a misleading number."""
    capital = float(startup_capital or 0)
    revenue = float(monthly_revenue_est or 0)
    if capital <= 0 or revenue <= 0:
        return None
    return max(1, round(capital / revenue))
