"""
app/services/recommendation_service.py
-----------------------------------------
Turns the numbers from forecasting_service.py -- PLUS the SME's own
input business parameters (industry and sub-category, what they sell,
what makes them different, an optional price list, capital, employee
count, business stage) compared against the real businesses already on
file for that industry/location (seeded market_data and/or live Google
Places API results) -- into the structured recommendation the capstone
paper's storyboard calls for: a headline, an opportunity type, a
one-sentence summary, a "Why This Works" reasons list, and a
"Considerations" risks list (see app/templates/sme/recommendations.html
and Reference/Figma_Storyboard's recommendations page).

THE FORECAST ITSELF, AND ITS TRANSCRIPT. Since the two-stage model
(app/services/plan_forecast_service.py, documented in
Reference/FORECAST_MODEL.md) every plan forecast carries a payload: the
market model's saturation, the trained plan model's viability, the
driver decomposition that says which inputs moved the score and by how
much, and the money figures (capital runway, ramp-up, fixed costs,
required daily sales, break-even window). That payload is stored in the
recommendation under "forecast" and is ALWAYS the model's -- an LLM
never writes or edits it. Next to it sits the FORECAST TRANSCRIPT,
stored under the key "explanation" (the name it had before it was
called a transcript; kept so every stored row still reads): a few
plain-language sentences in which Gemini transcribes the model's
computation -- what it forecast, how the numbers led there, what that
means for the owner.

A deterministic rule-based MODEL SUMMARY is always built from the
payload too. It is what stands when no AI transcript can be had (the
LLM switched off, no usable key, every attempt failed), and the page
labels it as exactly that. When the LLM is on, Gemini's transcript is
kept only if every number in it is one the model produced (see
ungrounded_numbers and review_transcript below); a draft that quotes
anything else is sent back once and then pruned rather than thrown
away (llm_service.transcribe_forecast). Either way the stored
"explanation" records who wrote it, in "generated_by".

The real schema has only ONE text column for this
(forecast_result.recommendation TEXT -- no separate reasons_json /
risks_json columns), so this module JSON-serializes the structured
dict into that single column (serialize_recommendation) and parses it
back out again (parse_recommendation) -- including a best-effort parse
of the OLD plain-text format this project used before this change, so
rows generated by an earlier version of the app still render correctly
instead of showing raw text or breaking the page.

Two modes, controlled by the use_llm_recommendations system setting
(Admin > System Settings, or USE_LLM_RECOMMENDATIONS in .env):

  - RULE-BASED (default, no API key needed): a deterministic dict
    built from the actual scores + the SME's own inputs. Free,
    offline, instant, and 100% reproducible -- good for a thesis
    defense where you need to explain exactly why the system said
    what it said.

  - LLM-ASSISTED (opt-in): calls app/services/llm_service.py to turn
    the SAME grounded numbers into a more naturally worded version of
    the same structured shape, plus the forecast explanation. Gemini is
    tried FIRST for this call (it is the AI this system names for
    narrating the forecast), then the provider configured in
    LLM_PROVIDER (GPT via OpenAI/OpenRouter, or Claude via Anthropic),
    then the rest. If every call fails for any reason (no key, no
    internet, quota, malformed JSON back), this silently falls back to
    the rule-based dict above -- the page never breaks because of this.
"""

import json
import numbers
import re
from collections import namedtuple
from datetime import datetime, timedelta, timezone

from app.models import SystemSetting

# Every recommendation dict -- rule-based, LLM-generated, or parsed back
# out of storage -- has exactly these keys, so every template that
# reads one (recommendations.html, home.html) can rely on the shape
# without checking for missing pieces.
#
# "forecast" is the trained model's payload (plan_forecast_service.
# forecast_plan) and "explanation" is {"text", "generated_by"}. Both are
# None on rows written before the two-stage model existed, and on any
# context built without a plan forecast.
_KEYS = ("headline", "opportunity_type", "summary", "reasons", "risks", "generated_by",
         "subcategory_analysis", "innovation", "forecast", "explanation", "competitor_insight")

# The provenance stamp on a transcript nobody's LLM wrote -- the
# rule-based model summary. Hyphenated (unlike the recommendation's own
# "rule_based") because it is matched by the templates as a label.
RULE_BASED_EXPLANATION = "rule-based"

# How long an AI transcript may run. The prompt asks for 5-8 sentences
# (two short paragraphs at most); this is the ceiling past which a reply
# is something other than that.
TRANSCRIPT_MAX_CHARS = 2000
# The least that still counts as a transcript once sentences quoting
# unverifiable figures have been dropped: fewer than this and what is
# left is a fragment, and the model summary is the better thing to show.
TRANSCRIPT_MIN_SENTENCES = 3
# After a failed upgrade of a stored forecast's AI text, how long the
# page waits before asking again. Each upgrade already retries a busy
# Gemini several times (llm_service), so a failure means a minute of
# trouble at least -- and every page view retrying it at once would
# spend whatever is left of the free tier's per-minute quota on requests
# that fail. Long enough for that window to pass, short enough that an
# owner looking at the plan sees Gemini's text appear (the page itself
# asks again when the wait is over, see forecast_transcript.js).
TRANSCRIPT_RETRY_AFTER = timedelta(minutes=2)
# The version of the Gemini request a failure stamp was made with. A
# stamp from an OLDER request says nothing about whether the current
# one works, so it is ignored and the forecast is retried at once. Bump
# this whenever the request itself is fixed. 3: retried sends, the
# longer timeout, and the recommendation upgraded with the transcript.
TRANSCRIPT_REQUEST_VERSION = 3
# The time one forecast run (plan saved or edited) may spend on the AI,
# and the time one background upgrade may (POST /api/forecasts/<id>/
# transcript). Each covers the recommendation call and the dedicated
# transcript call together -- see llm_service.ai_time_budget.
AI_TIME_BUDGET_AT_FORECAST = 80
AI_TIME_BUDGET_FOR_UPGRADE = 95


# ---------------------------------------------------------------------
# 1. Context building -- gathers the SME's OWN input parameters and the
#    real comparison data (competitor sample, population) into the one
#    dict both the rule-based generator and the LLM prompt read from.
# ---------------------------------------------------------------------

def price_summary(items):
    """{count, priced, low, high} for the optional price list, or None.
    Only the owner's own figures -- no market price benchmark is
    invented to compare them against."""
    items = [i for i in (items or []) if isinstance(i, dict) and i.get("item")]
    if not items:
        return None
    prices = [float(i["price"]) for i in items if i.get("price") is not None]
    return {
        "count": len(items),
        "priced": len(prices),
        "low": min(prices) if prices else None,
        "high": max(prices) if prices else None,
    }


def _profile_capital(sme_profile):
    """The plan's capital as a float. SmeProfile.capital is the read
    property over the startup_capital column (the column keeps its old
    name because renaming a live MySQL column is a destructive
    migration); the column itself is the fallback for any object that
    does not have the property."""
    capital = getattr(sme_profile, "capital", None)
    if capital is None:
        capital = getattr(sme_profile, "startup_capital", None)
    try:
        return float(capital or 0)
    except (TypeError, ValueError):
        return 0.0


def _capital(context):
    """Capital from a context, whichever spelling built it. Contexts
    written before the rename (and hand-built test contexts) only have
    "startup_capital"."""
    value = context.get("capital")
    if value is None:
        value = context.get("startup_capital")
    try:
        return float(value or 0)
    except (TypeError, ValueError):
        return 0.0


def build_recommendation_context(sme_profile, scores, competitor_sample=None, competitor_simulated=True,
                                  population=0, subcategory_analysis=None, plan_forecast=None):
    """`sme_profile` is the SME's own SmeProfile row (their input
    business parameters). `scores` is the dict compute_scores() in
    forecasting_service.py just returned for that same profile -- after
    the sub-category adjustment, when there is one (see
    subcategory_service.adjusted_scores), in which case it also carries
    industry_saturation_index for the comparison.
    `competitor_sample` is a short list of real (or simulated,
    clearly flagged) business names on file for this industry+location
    -- see forecasting_service.generate_forecast_for_profile().
    `subcategory_analysis` is subcategory_service.direct_competition()'s
    result, or None when the plan has no sub-category.
    `plan_forecast` is plan_forecast_service.forecast_plan()'s payload
    -- the trained plan model's output -- or None for a caller that has
    not run it (the explanation and the capital/pricing lines are then
    simply absent, and the rest reads exactly as before).

    "capital" is the name used everywhere now. "startup_capital" stays
    in the dict as an alias with the same value, because hand-built
    contexts elsewhere (and older code paths) still read that key.

    Monthly revenue is deliberately absent: it is no longer collected
    (see app/services/plan_params.py)."""
    offering_items = list(getattr(sme_profile, "offering_items", None) or [])
    capital = _profile_capital(sme_profile)
    return {
        "business_name": sme_profile.business_name,
        "industry_type": sme_profile.industry_type,
        "subcategory": getattr(sme_profile, "subcategory", None),
        "subcategory_label": getattr(sme_profile, "subcategory_label", None),
        "product_offering": getattr(sme_profile, "product_offering", None) or "",
        "innovation_idea": getattr(sme_profile, "innovation_idea", None) or "",
        "offering_items": offering_items,
        "price_summary": price_summary(offering_items),
        "location": sme_profile.location,
        "business_stage": sme_profile.business_stage,
        "years_in_operation": sme_profile.years_in_operation(),
        "capital": capital,
        "startup_capital": capital,
        "employee_count": sme_profile.employee_count or 0,
        "saturation_index": scores["saturation_index"],
        "industry_saturation_index": scores.get("industry_saturation_index", scores["saturation_index"]),
        "cluster_label": scores["cluster_label"],
        "viability_score": scores["viability_score"],
        "confidence_level": scores["confidence_level"],
        "population": int(population or 0),
        "competitor_count": scores["competitor_count"],
        "competitor_simulated": competitor_simulated,
        "competitor_sample": competitor_sample or [],
        "subcategory_analysis": subcategory_analysis,
        "forecast": plan_forecast if isinstance(plan_forecast, dict) else None,
    }


# ---------------------------------------------------------------------
# 2. Rule-based generator -- always available, no API key needed. This
#    is also what every LLM call ultimately falls back to.
# ---------------------------------------------------------------------

def _headline_and_type_for(cluster_label):
    if cluster_label == "Saturated":
        return ("HIGH SATURATION -- avoid this market or pivot to a clearly differentiated niche.",
                "High Saturation")
    if cluster_label == "High":
        return ("MODERATE-HIGH SATURATION -- consider a niche angle or a nearby underserved location.",
                "Moderate Opportunity")
    if cluster_label == "Moderate":
        return ("MODERATE OPPORTUNITY -- viable with a solid differentiation strategy.",
                "Moderate Opportunity")
    return ("HIGH OPPORTUNITY -- favorable conditions for market entry.", "High Opportunity")


def _kind_of_business(context):
    """"a bakery" when a sub-category is known, else "a food and beverage
    business" -- the summary should name what the owner actually said
    they are opening."""
    label = context.get("subcategory_label")
    if context.get("subcategory") and context.get("subcategory") != "other" and label:
        return label.lower()
    return f"{context['industry_type'].lower()} business"


def _number(value, default=None):
    """A payload figure as a plain float, or `default` when it is
    missing or not a number. The payload is the model agent's contract
    and is JSON-safe, but a row stored by an earlier build may lack a
    key, and the writers below must never raise over that."""
    if value is None or isinstance(value, bool):
        return default
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def _figure(value, places=1):
    """A payload figure as prose quotes it: whole numbers without a
    decimal point, anything else to `places` decimals, with thousands
    separators. Quoting the payload's own rounding (rather than
    re-rounding to something prettier) is what lets the explanation
    pass the same grounding check the LLM's wording has to pass."""
    value = float(value or 0)
    if value.is_integer():
        return f"{value:,.0f}"
    return f"{value:,.{places}f}"


def _peso(value):
    """₱ amounts: whole pesos when the figure is whole or large,
    centavos only for small prices that actually have them."""
    value = float(value or 0)
    if value.is_integer() or abs(value) >= 1000:
        return f"₱{value:,.0f}"
    return f"₱{value:,.2f}"


def _plural(count, word):
    count = int(count or 0)
    return f"{count} {word}" + ("" if count == 1 else "s")


def _join(parts):
    """"a", "a and b", "a, b and c"."""
    parts = [p for p in parts if p]
    if len(parts) <= 1:
        return "".join(parts)
    return ", ".join(parts[:-1]) + " and " + parts[-1]


def _forecast(context):
    """The trained model's payload from a context, or None."""
    forecast = context.get("forecast")
    return forecast if isinstance(forecast, dict) else None


def _plan_model_is_trained(forecast):
    """True when the plan stage was the trained forest; False for the
    scorecard-formula fallback used while no plan_model.pkl exists. The
    prose says which, rather than calling a formula a trained model."""
    plan = forecast.get("plan") or {}
    return str(plan.get("model_version") or "").startswith("plan_rf")


def _market_model_is_trained(forecast):
    """The same question for the market stage: True for the trained
    forest ("rf_v1"), False for forecasting_service's weighted-formula
    fallback ("formula_v1") used while no rf_model.pkl exists. Asked
    separately because the two stages can each be missing on their own
    -- a trained plan model sitting on a formula market reading is a
    real state, and the prose must not call that formula a model."""
    market = forecast.get("market") or {}
    return str(market.get("model_version") or "").startswith("rf")


def _capital_and_pricing_lines(context):
    """(reasons, risks) about the two things the plan model weighs that
    the market model never sees: whether the capital carries the plan
    through its ramp-up, and whether the price list can cover the fixed
    costs at a sales volume the barangay can plausibly support.

    Every figure quoted is the payload's own -- runway, ramp-up, fixed
    cost, required daily sales, daily sales ceiling -- so these lines
    can never disagree with the forecast they sit under. Empty when the
    context carries no plan forecast."""
    forecast = _forecast(context)
    if forecast is None:
        return [], []
    financials = forecast.get("financials") or {}
    inputs = forecast.get("inputs") or {}
    reasons, risks = [], []

    capital = _number(inputs.get("capital"), _capital(context))
    runway = _number(financials.get("capital_runway_months"), 0.0)
    ramp = _number(financials.get("ramp_up_months"))
    fixed_cost = _number(financials.get("monthly_fixed_cost"))
    if ramp is not None and fixed_cost is not None:
        if capital <= 0:
            risks.append(
                f"no capital is on file for this plan, so the forecast counts no runway against the "
                f"~{_figure(ramp)}-month ramp-up the model expects -- add your capital for an accurate forecast"
            )
        elif runway >= ramp:
            reasons.append(
                f"your capital of {_peso(capital)} covers about {_figure(runway)} months of fixed costs "
                f"({_peso(fixed_cost)}/month), longer than the ~{_figure(ramp)}-month ramp-up the model expects"
            )
        else:
            risks.append(
                f"your capital of {_peso(capital)} covers only about {_figure(runway)} months of fixed costs "
                f"({_peso(fixed_cost)}/month), shorter than the ~{_figure(ramp)}-month ramp-up the model "
                f"expects -- more capital, fewer staff at the start, or a cheaper site would close the gap"
            )

    priced = int(_number(inputs.get("priced_item_count"), 0) or 0)
    required = _number(financials.get("required_daily_sales"), 0.0)
    ceiling = _number(financials.get("daily_sales_ceiling"), 0.0)
    average = _number(inputs.get("average_price"), 0.0)
    if priced > 0 and required > 0:
        need = (f"at an average price of {_peso(average)} you need about {_figure(required)} sales a day "
                f"to cover fixed costs")
        if ceiling <= 0:
            risks.append(f"{need}, and no local demand ceiling could be estimated for {context['location']}")
        elif required <= ceiling / 2:
            reasons.append(f"{need} -- well within the ~{_figure(ceiling)} a day this barangay's residents "
                           f"could plausibly support")
        elif required <= ceiling:
            risks.append(f"{need} -- more than half of the ~{_figure(ceiling)} a day this barangay's residents "
                         f"could plausibly support, so there is little slack; higher-margin items or lower "
                         f"fixed costs would ease it")
        else:
            risks.append(f"{need} -- more than the ~{_figure(ceiling)} a day this barangay's residents could "
                         f"plausibly support; raise prices, add higher-value items or cut fixed costs")
    return reasons, risks


def _summary_for(context):
    forecast = _forecast(context)
    if forecast is not None:
        plan = forecast.get("plan") or {}
        viability = _number(plan.get("viability_score"), _number(context.get("viability_score"), 0.0))
        writer = "the trained plan model" if _plan_model_is_trained(forecast) else "the plan scorecard"
        summary = (
            f"A {_kind_of_business(context)} in {context['location']} is currently classified as "
            f"'{context['cluster_label']}' saturation ({round(context['saturation_index'])}%); once your "
            f"capital, staffing, pricing and offering are factored in, {writer} puts its viability at "
            f"{_figure(viability)}/10."
        )
    else:
        summary = (
            f"A {_kind_of_business(context)} in {context['location']} is currently classified as "
            f"'{context['cluster_label']}' saturation ({round(context['saturation_index'])}%), with a viability "
            f"score of {context['viability_score']}/10 for the parameters you entered."
        )
    analysis = context.get("subcategory_analysis")
    if analysis and analysis.get("adjusts_score"):
        summary += (
            f" Industry-wide the figure is {round(context['industry_saturation_index'])}%; it moves because "
            f"direct {analysis['label'].lower()} competition here is "
            f"{'lighter' if analysis['density_ratio'] < 1 else 'heavier'} than usual."
        )
    return summary


def _reasons_for(context):
    cluster_label = context["cluster_label"]
    industry_lower = context["industry_type"].lower()
    reasons = []
    if cluster_label in ("Low", "Moderate"):
        reasons.append(f"only {context['competitor_count']} existing {industry_lower} business(es) found "
                        f"in {context['location']}")
        if context["population"]:
            reasons.append(f"a real population of {context['population']:,} gives room for a new entrant")
        else:
            reasons.append("demand indicators suggest room for a new entrant")
    else:
        reasons.append(f"{context['competitor_count']} existing {industry_lower} business(es) already "
                        f"serve {context['location']}")
    analysis = context.get("subcategory_analysis")
    if analysis and not analysis.get("is_estimated") and analysis.get("density_ratio", 1) < 1:
        reasons.append(
            f"only {analysis['direct_count']} direct {analysis['label'].lower()} competitor(s) measured in "
            f"{context['location']} -- fewer than its {analysis['industry_count']} "
            f"{industry_lower} businesses would normally hold"
        )
    if _forecast(context) is not None:
        # The plan model weighed the capital against the ramp-up, so
        # say what it found rather than only that a figure exists.
        reasons.extend(_capital_and_pricing_lines(context)[0])
    elif _capital(context):
        reasons.append(f"your capital of PHP {_capital(context):,.0f} is on file for this plan")
    reasons.append(f"model confidence for this estimate is {round(context['confidence_level'])}%")
    return reasons


def _risks_for(context):
    cluster_label = context["cluster_label"]
    risks = []
    if cluster_label in ("High", "Saturated"):
        risks.append(f"the market is already {round(context['saturation_index'])}% saturated in "
                      f"{context['location']}")
        risks.append("expect strong price/brand competition from existing businesses")
    else:
        risks.append("initial brand-awareness building will still be required")
        risks.append("monitor seasonal demand fluctuations after launch")
    analysis = context.get("subcategory_analysis")
    if analysis:
        if analysis.get("is_estimated"):
            risks.append(
                f"the direct {analysis['label'].lower()} competitor count (~{analysis['direct_count']}) is an "
                f"estimate -- no sub-category count is on file for {context['location']} yet, so the score "
                f"is the industry-wide one"
            )
        elif analysis.get("density_ratio", 1) > 1:
            risks.append(
                f"{analysis['direct_count']} direct {analysis['label'].lower()} competitor(s) in "
                f"{context['location']} -- denser than usual for its {analysis['industry_count']} "
                f"{context['industry_type'].lower()} businesses"
            )
    risks.extend(_capital_and_pricing_lines(context)[1])
    if context["competitor_simulated"]:
        risks.append("competitor count for this area is a simulated estimate -- connect a live Google "
                      "Places API key for exact figures")
    return risks


# How much a new entrant has to stand out, by the saturation tier the
# model put this plan in. Read from the model's own output -- the only
# market fact the rule-based writer has -- not from the idea's wording,
# which it cannot judge. Judging the idea itself is the LLM's job.
_DIFFERENTIATION_NEED = {
    "Saturated": "Very high",
    "High": "High",
    "Moderate": "Moderate",
    "Low": "Low",
}

_DIFFERENTIATION_SUGGESTIONS = {
    "Very high": [
        "make the difference visible before anyone buys -- signage, packaging or a sample customers can try",
        "test the idea with a small batch or a weekend stall before committing the full capital",
        "pick one thing to be known for rather than competing on everything the established shops offer",
    ],
    "High": [
        "lead with the difference in your name, signage and first posts, so it is what people remember",
        "price the new item so trying it is an easy yes next to what regulars already buy",
        "ask your first customers what made them choose you, and double down on that",
    ],
    "Moderate": [
        "the market has room, so the idea is a head start rather than a lifeline -- consistency matters as much",
        "keep the idea simple enough to deliver the same way every day",
    ],
    "Low": [
        "competition is light, so reliability and convenience can matter more than novelty at first",
        "keep the idea as a way to hold customers once competitors arrive",
    ],
}


def _rule_based_innovation(context):
    """What the plan's differentiation is up against. The rule-based
    writer does NOT rate how new the idea is -- it has no way to know --
    so `novelty` stays None here and only the LLM fills it in."""
    need = _DIFFERENTIATION_NEED.get(context["cluster_label"], "Moderate")
    analysis = context.get("subcategory_analysis")
    if analysis:
        rivals = f"{'about ' if analysis.get('is_estimated') else ''}{analysis['direct_count']} direct " \
                 f"{analysis['label'].lower()} competitor(s)"
    else:
        rivals = f"{context['competitor_count']} {context['industry_type'].lower()} business(es)"

    idea = (context.get("innovation_idea") or "").strip()
    if idea:
        summary = (
            f"Your idea goes up against {rivals} in {context['location']}, where the market is "
            f"{round(context['saturation_index'])}% saturated -- differentiation need: {need.lower()}."
        )
    else:
        summary = (
            f"You have not said what makes the business different yet. With {rivals} in "
            f"{context['location']}, differentiation need is {need.lower()} -- add your idea to the plan "
            f"for a clearer read."
        )

    prices = context.get("price_summary")
    if prices and prices.get("priced"):
        if prices["low"] == prices["high"]:
            summary += f" Your price list has {prices['count']} item(s) at PHP {prices['low']:,.2f}."
        else:
            summary += (f" Your price list has {prices['count']} item(s), from PHP {prices['low']:,.2f} "
                        f"to PHP {prices['high']:,.2f}.")

    return {
        "has_idea": bool(idea),
        "differentiation_need": need,
        "novelty": None,
        "summary": summary,
        "suggestions": list(_DIFFERENTIATION_SUGGESTIONS.get(need, [])),
        "generated_by": "rule_based",
    }


# ---------------------------------------------------------------------
# 2a. The competitor insight -- "how many of you are already here, and
#     can this plan still win?"
# ---------------------------------------------------------------------
# The Planning page shows it SHORT (one or two sentences next to the
# direct-competitor count) and the Recommendations page shows it IN FULL,
# so the two pages say the same thing at two lengths rather than two
# different things.
#
# The AI writes both (llm_service asks for "competitor_insight"), because
# the judgement it needs -- is THIS pandesal idea new against the
# pandesal shops already trading here? -- is a reading of words, which a
# template cannot do. This rule-based version is what stands when the AI
# is off or its text quotes a figure it was not given; it says only what
# the numbers say, and names the novelty only when the AI rated it.
#
# Built from STORED fields alone (the sub-category analysis, the market
# payload, the innovation read), so parse_recommendation() can give a
# forecast written before this existed the same insight.

def competitor_insight_from(analysis, competitor_count, industry_type, location, innovation):
    """{"short", "detail", "generated_by", "label", "direct_count",
    "industry_count", "is_estimated", "source"} -- the rule-based insight."""
    innovation = innovation or {}
    has_idea = bool(innovation.get("has_idea"))
    novelty = innovation.get("novelty")
    need = (innovation.get("differentiation_need") or "Moderate").lower()
    industry_count = int(_number(competitor_count, 0) or 0)
    location = location or "this barangay"

    if analysis:
        label = str(analysis.get("label") or "Direct competitor")
        direct = int(_number(analysis.get("direct_count"), 0) or 0)
        estimated = bool(analysis.get("is_estimated"))
        kind = label.lower()
        ratio = _number(analysis.get("density_ratio"), 1.0) or 1.0
        if estimated:
            crowd = ("No count of this exact kind of business is on file for this barangay yet, "
                     "so that number is an estimate.")
        elif ratio < 1:
            crowd = ("That is fewer than a barangay with this many businesses usually has, so direct "
                     "competition is lighter than the industry figure suggests.")
        elif ratio > 1:
            crowd = ("That is more than a barangay with this many businesses usually has, so direct "
                     "competition is heavier than the industry figure suggests.")
        else:
            crowd = "That is about what is usual for a barangay with this many businesses."
    else:
        label = industry_type or "Competitor"
        direct = industry_count
        estimated = False
        kind = (industry_type or "business").lower()
        crowd = "Pick a sub-category on the plan to count only the businesses that sell what you sell."
    count_text = f"{'About ' if estimated else ''}{direct} {kind} business{'es' if direct != 1 else ''}"

    if novelty == "High":
        chance_short = "Your idea reads as genuinely new here, so the plan has a real chance."
        chance = ("Your idea reads as genuinely new here, so even with that competition the plan has a "
                  "real chance, provided customers can see the difference from day one.")
    elif novelty == "Moderate":
        chance_short = "Your idea is partly new here and can set you apart."
        chance = ("Your idea is partly new here: it can set you apart, but expect competitors to copy what "
                  "works, so make it the thing you are known for.")
    elif novelty == "Low":
        chance_short = "Your idea looks close to what is already offered, so sharpen the difference."
        chance = ("Your idea looks close to what is already offered here, so it will not set you apart on "
                  "its own; sharpen the difference before you open.")
    elif has_idea:
        chance_short = f"Your idea is what has to set you apart (differentiation need: {need})."
        chance = (f"You have described what makes you different; with a differentiation need of {need}, "
                  "that idea is what has to carry the plan against them.")
    else:
        chance_short = f"Add what makes you different for a clearer read (differentiation need: {need})."
        chance = (f"You have not said what makes you different yet, and the differentiation need here is "
                  f"{need}. Add your idea to the plan for a clearer read.")

    return {
        "short": f"{count_text} already trade in {location}. {chance_short}",
        "detail": f"{count_text} already trade in {location}. {crowd} {chance}",
        "generated_by": RULE_BASED_EXPLANATION,
        "label": label,
        "direct_count": direct,
        "industry_count": industry_count,
        "is_estimated": estimated,
        "source": (analysis or {}).get("source"),
    }


def _rule_based_competitor_insight(context, innovation):
    return competitor_insight_from(
        context.get("subcategory_analysis"), context.get("competitor_count"),
        context.get("industry_type"), context.get("location"), innovation,
    )


def _choose_competitor_insight(llm_value, writer, rule_insight, context):
    """The AI's insight when it is present and quotes only figures it was
    given (the same check as the transcript), else the rule-based one.
    A sentence quoting a figure it was not given is dropped rather than
    the whole insight, as long as both the short and the full form still
    say something. The counts shown beside it are always the measured
    ones."""
    if not isinstance(llm_value, dict):
        return rule_insight
    short = " ".join(str(llm_value.get("short") or "").split())
    detail = " ".join(str(llm_value.get("detail") or "").split())
    if not short or not detail or len(short) > 400 or len(detail) > TRANSCRIPT_MAX_CHARS:
        return rule_insight
    if ungrounded_numbers(short + " " + detail, context):
        allowed = _grounding_numbers(context)

        def grounded_sentences(text):
            return " ".join(sentence for sentence in _sentences(text)
                            if all(_matches(figure, allowed) for figure in _numbers_in(sentence)))

        short, detail = grounded_sentences(short), grounded_sentences(detail)
        if not short or not detail:
            return rule_insight
    return {**rule_insight, "short": short, "detail": detail, "generated_by": writer}


# ---------------------------------------------------------------------
# 2b. The forecast explanation -- a transcription of what the trained
#     model said and why, written from the payload alone.
# ---------------------------------------------------------------------

def _rule_based_explanation_text(context):
    """Four to six plain sentences built ONLY from the forecast payload:
    the plan's viability and confidence, the market saturation and its
    tier, the largest drivers with their signs, the capital runway
    against the ramp-up (with the fixed cost broken into rent and
    payroll), the required daily sales against the ceiling when there is
    a price list, and the break-even window.

    Deterministic: the same payload always produces the same words, so
    this is the version that can be defended line by line -- and the
    one that stands whenever the LLM is off, fails, or quotes a number
    the model never produced. None when the context has no payload."""
    forecast = _forecast(context)
    if forecast is None:
        return None
    market = forecast.get("market") or {}
    plan = forecast.get("plan") or {}
    financials = forecast.get("financials") or {}
    inputs = forecast.get("inputs") or {}
    trained = _plan_model_is_trained(forecast)
    sentences = []

    # 1. The verdict. Each confidence is credited to the stage that
    #    produced it: the plan stage's own figure goes with the plan's
    #    viability, and when the market stage is the less sure of the
    #    two, the forecast's overall confidence -- the lower of the two,
    #    since a forecast is only as sure as its weaker half, and the
    #    figure stored on the forecast and shown beside it -- is named
    #    as the market stage's rather than passed off as the plan's.
    viability = _number(plan.get("viability_score"), _number(context.get("viability_score"), 0.0))
    market_confidence = _number(market.get("confidence"))
    plan_confidence = _number(plan.get("confidence"))
    verdict = ("The trained plan model rates this plan's viability" if trained else
               "The plan scorecard formula (no trained plan model is available yet) rates this plan's viability")
    verdict += f" {_figure(viability)}/10"
    market_stage = "market model" if _market_model_is_trained(forecast) else "market formula"
    if plan_confidence is not None:
        verdict += f" with {_figure(plan_confidence)}% confidence"
        if market_confidence is not None and market_confidence < plan_confidence:
            verdict += (f"; the forecast's overall confidence is {_figure(market_confidence)}%, the "
                        f"{market_stage}'s, since a forecast is only as sure as its less certain stage")
    elif market_confidence is not None:
        verdict += f"; the forecast's overall confidence is {_figure(market_confidence)}%, the {market_stage}'s"
    sentences.append(verdict + ".")

    # 2. The market stage it started from -- named for what produced it:
    #    the trained market forest, or the weighted formula that stands
    #    in for it while no rf_model.pkl exists.
    saturation = _number(market.get("saturation_index"), _number(context.get("saturation_index"), 0.0))
    tier = market.get("cluster_label") or context.get("cluster_label")
    location = inputs.get("location") or context.get("location")
    reader = ("The market model" if _market_model_is_trained(forecast) else
              "The market formula (no trained market model is available yet)")
    market_line = f"{reader} reads {location} as {_figure(saturation)}% saturated for this kind of business"
    if tier:
        market_line += f" (the '{tier}' tier)"
    industry = _number(market.get("industry_saturation_index"))
    if industry is not None and abs(industry - saturation) >= 0.05:
        market_line += f", against {_figure(industry)}% for the industry as a whole"
    sentences.append(market_line + ".")

    # 3. The drivers -- the exact decomposition of the forest's answer,
    #    or the scorecard's weighted components when no forest exists.
    drivers = [d for d in (forecast.get("drivers") or [])
               if isinstance(d, dict) and d.get("label") and abs(_number(d.get("points"), 0.0)) >= 0.05][:3]
    if drivers:
        def _label(d):
            text = str(d["label"])
            return text[:1].lower() + text[1:]

        if trained:
            parts = [f"{_label(d)} {'added' if _number(d['points']) > 0 else 'took off'} "
                     f"{_figure(abs(_number(d['points'])))} points" for d in drivers]
            baseline = _number(forecast.get("baseline"))
            opener = (f"Starting from the model's baseline of {_figure(baseline)} points, "
                      if baseline is not None else "Of the plan's inputs, ")
            sentences.append(f"{opener}{_join(parts)}.")
        else:
            parts = [f"{_label(d)} ({_figure(abs(_number(d['points'])))} points)" for d in drivers]
            sentences.append(f"The largest parts of the scorecard were {_join(parts)}.")

    # 4. Capital against the ramp-up, with the fixed cost broken down.
    fixed_cost = _number(financials.get("monthly_fixed_cost"))
    ramp = _number(financials.get("ramp_up_months"))
    if fixed_cost is not None and ramp is not None:
        rent = _number(financials.get("monthly_rent"), 0.0)
        employees = int(_number(inputs.get("employee_count"), _number(context.get("employee_count"), 0)) or 0)
        wage = _number(financials.get("daily_wage"), 0.0)
        days = _number(financials.get("operating_days"), 0.0)
        if employees:
            cost = (f"{_peso(fixed_cost)}/month (rent {_peso(rent)} plus {_plural(employees, 'employee')} "
                    f"× {_peso(wage)}/day × {_figure(days)} days)")
        else:
            cost = f"{_peso(fixed_cost)}/month (rent {_peso(rent)}; no paid staff yet)"
        capital = _number(inputs.get("capital"), _capital(context))
        if capital <= 0:
            sentences.append(
                f"No capital is on file, so against fixed costs of {cost} the model counted no runway for the "
                f"~{_figure(ramp)}-month ramp-up it expects -- add your capital for an accurate forecast."
            )
        else:
            runway = _number(financials.get("capital_runway_months"), 0.0)
            comparison = "longer than" if runway >= ramp else "shorter than"
            sentences.append(
                f"Fixed costs come to {cost}, so your capital of {_peso(capital)} covers about "
                f"{_figure(runway)} months -- {comparison} the ~{_figure(ramp)}-month ramp-up the model expects."
            )

    # 5. Pricing, when there is a price list to read.
    priced = int(_number(inputs.get("priced_item_count"), 0) or 0)
    required = _number(financials.get("required_daily_sales"), 0.0)
    if priced > 0 and required > 0:
        margin = _number(financials.get("gross_margin"))
        ceiling = _number(financials.get("daily_sales_ceiling"), 0.0)
        pricing = f"At your average price of {_peso(_number(inputs.get('average_price'), 0.0))}"
        if margin is not None:
            pricing += f" and a {_figure(round(margin * 100, 1))}% gross margin"
        pricing += f", covering those costs takes about {_figure(required)} sales a day"
        if ceiling > 0:
            pricing += (f", {'within' if required <= ceiling else 'more than'} the ~{_figure(ceiling)} a day "
                        f"this barangay's residents could plausibly support")
        sentences.append(pricing + ".")
    elif fixed_cost is not None:
        # "Neutral" is true only of the scorecard, which gives an unknown
        # price coverage a middle score (C3 = 0.5). The trained forest
        # measures every input against its baseline -- the average plan
        # it learned from -- so a missing price list can and usually does
        # cost points there, and the drivers sentence above already says
        # so with its sign. Calling that "neutral" would contradict the
        # very paragraph it sits in; say only what is true either way.
        if trained:
            sentences.append("No prices are listed yet, so your prices could not be checked against your "
                             "fixed costs or what local demand can support.")
        else:
            sentences.append("No prices are listed yet, so the scorecard treated pricing as neutral "
                             "(a middle score).")

    # 6. Where it all lands.
    break_even = financials.get("break_even") or {}
    if isinstance(break_even, dict) and break_even.get("label"):
        sentences.append(f"Taken together, the model's break-even window for this plan is {break_even['label']}.")

    return " ".join(sentences)


def _rule_based_explanation(context):
    text = _rule_based_explanation_text(context)
    if not text:
        return None
    return {"text": text, "generated_by": RULE_BASED_EXPLANATION}


# THE GROUNDING CHECK.
#
# The LLM is asked to transcribe the model's output "using only the
# numbers given". Asking is not checking: a fluent paragraph with one
# invented figure in it ("you will break even in 6 months") reads exactly
# as convincingly as a faithful one, and is precisely the failure an
# explanation must never have. So every number in the LLM's text --
# written in digits OR in words ("six months", "two million pesos") -- is
# matched against the numbers the model and the owner actually supplied.
# One that matches nothing discards the whole explanation in favour of
# the rule-based one.
#
# WHICH numbers it may match is the first half of the check: the figures
# the prompt SHOWS the LLM -- the context (the owner's inputs and the
# market comparison) and the payload -- less the few payload figures the
# prompt never prints (_UNSHOWN_PAYLOAD below) and the sub-category
# analysis's internals (_UNSHOWN_ANALYSIS). Those are real, but the
# LLM has never seen them, so a sentence that "matches" one matched by
# accident: the scorecard's seven component weights (0.40, 0.20, 0.10,
# 0.08, 0.07...) and scores sit in every payload, and counting them
# grounded "break even in 8 months" and "scores 8/10" on every plan.
#
# WHAT counts as a match is the second half, deliberately narrow, and
# each allowance has a reason:
#   * +/-0.6 absolute or +/-2% relative -- the payload holds 8.2 and the
#     text says "8.2", or 61,020 written as "61,020"; 42.1% quoted as
#     "42%" is rounding, not invention;
#   * x10 / /10, for the viability only -- it is shown both as a 0-100
#     index and as a 0-10 score, and "6.1" and "61" are the same figure;
#   * the gross margin as a percentage -- the prompt prints 0.4 as
#     "40%", so "40%" matches it; but only a number written WITH a
#     percent sign (or "percent") does, so the margin cannot ground "40
#     months". No other fraction becomes a percentage;
#   * an INTEGER of 12 or less ("3 employees", "8 months", "six") gets
#     none of the slack above -- no x10, no /10, no percentage -- only
#     ordinary rounding of a value the context itself holds: small
#     integers are cheap to hit by accident, so "3" passes only when the
#     context holds something between 2.5 and 3.5.
# Denominators ("/10", "out of 100", "out of ten") are not figures and
# are dropped first; nor is "one" used as a pronoun ("one of the
# drivers", "no one"). What the check cannot read -- "twice", "half the
# ceiling", a unit converted ("a year" for 12 months) -- it does not
# pretend to; those are left to the prompt's instruction to copy every
# figure exactly as written.
#
# HOW MONEY IS WRITTEN is read generously, because the cost of reading
# too little is an invented figure on the page, and the cost of reading
# too much is only the rule-based paragraph instead of the LLM's:
#   * a peso prefix in any case, glued or spaced -- "PHP500", "Php
#     2,400,000", "php500", "P500" -- is the peso sign;
#   * a magnitude suffix in any case: glued "500k", "3.4m", "2.4bn",
#     "1.5mil"; spaced "8.3 M", "2.4 mn", "2 Bn"; or a word, "1.5
#     million", "2 mil". "k" counts only glued to the digits, and a
#     lone spaced "m" or "b" not at all, so "5 km" and "a 5 m frontage"
#     are not read as thousands or millions;
#   * digits glued to letters ARE figures -- "x25", "USD500" -- unless
#     the word they sit in is a code: a version or identifier ("v1",
#     "rf_v1", anything with an underscore), a quarter ("Q1".."Q4"), or
#     digits between letters ("B2B").

_DENOMINATOR_RE = re.compile(r"\s*(?:/|\bout of)\s*(?:10{1,2}|ten|(?:a|one) hundred)\b", re.I)
_NUMBER_RE = re.compile(
    r"(?<![\d.,])(\d{1,3}(?:,\d{3})+(?:\.\d+)?|\d+(?:\.\d+)?)"
    r"((?i:k|mn|mil|m|bn|b)\b"
    r"|\s(?:[Mm]n|MN|[Bb]n|BN|M|B)\b"
    r"|\s(?i:billion|million|thousand|hundred|mil)\b)?"
)
_PESO_PREFIX_RE = re.compile(r"\bphp\.?\s*(?=\d)|\bp(?=\d)", re.I)
_CODE_WORD_RE = re.compile(r"v\d+|q[1-4]|[a-z]+\d+[a-z]+", re.I)
_MAGNITUDES = {
    "hundred": 100, "k": 1_000, "thousand": 1_000,
    "m": 1_000_000, "mn": 1_000_000, "mil": 1_000_000, "million": 1_000_000,
    "b": 1_000_000_000, "bn": 1_000_000_000, "billion": 1_000_000_000,
}
_PERCENT_RE = re.compile(r"\s?(?:%|per\s?cent\b)", re.I)
_SMALL_INTEGER = 12

# Numbers written in words. Ordinals ("first", "second") are positions,
# not figures, and are deliberately absent.
_WORD_VALUES = {
    "zero": 0, "one": 1, "two": 2, "three": 3, "four": 4, "five": 5, "six": 6, "seven": 7,
    "eight": 8, "nine": 9, "ten": 10, "eleven": 11, "twelve": 12, "thirteen": 13,
    "fourteen": 14, "fifteen": 15, "sixteen": 16, "seventeen": 17, "eighteen": 18,
    "nineteen": 19, "twenty": 20, "thirty": 30, "forty": 40, "fifty": 50, "sixty": 60,
    "seventy": 70, "eighty": 80, "ninety": 90,
}
_WORD_SCALES = {"hundred": 100, "thousand": 1_000, "million": 1_000_000, "billion": 1_000_000_000}
_NUMBER_WORDS = frozenset(_WORD_VALUES) | frozenset(_WORD_SCALES) | {"dozen"}
_WORD_RE = re.compile(r"[A-Za-z]+")
# "one" in this company is a pronoun ("no one", "each one", "one of the
# drivers"), not a count -- and it is common enough in plain prose that
# reading it as the figure 1 would discard honest paragraphs for nothing.
_PRONOUN_ONE_AFTER = frozenset({"no", "any", "each", "every", "the", "this", "that", "which"})
_PRONOUN_ONE_BEFORE = frozenset({"of", "another"})

# A number as the check reads it: its value, whether it is a small
# integer (see above), whether it was written as a percentage, and the
# text exactly as written (what the log line reports).
_Figure = namedtuple("_Figure", "value small percent written")


def _spelled_numbers(text):
    """[(start, end, value, scaled), ...] for every number written in
    words: "six", "twenty-five", "two hundred and fifty thousand", "a
    dozen", "one and a half". A run is number words joined only by a
    space or a hyphen -- "and" only after hundred/thousand/million, as in
    "two hundred and fifty" -- so "between six and nine months" stays two
    numbers rather than becoming fifteen. `scaled` is True when a scale
    word or a half is involved (the figure is then never a small
    integer)."""
    words = [(m.group(0).lower(), m.start(), m.end()) for m in _WORD_RE.finditer(text)]

    def joined(a, b):
        gap = text[words[a][2]:words[b][1]]
        return bool(gap) and re.fullmatch(r"[ \t]*-?[ \t]*", gap) is not None

    found, i = [], 0
    while i < len(words):
        k, run = i, []
        # "a dozen", "a hundred", "a million": the article is the one.
        if words[k][0] in ("a", "an") and k + 1 < len(words) and joined(k, k + 1) \
                and (words[k + 1][0] in _WORD_SCALES or words[k + 1][0] == "dozen"):
            run.append("one")
            k += 1
        if words[k][0] not in _NUMBER_WORDS:
            i += 1
            continue
        run.append(words[k][0])
        k += 1
        while k < len(words):
            if words[k][0] in _NUMBER_WORDS and joined(k - 1, k):
                run.append(words[k][0])
                k += 1
            elif (words[k][0] == "and" and run[-1] in _WORD_SCALES and k + 1 < len(words)
                  and words[k + 1][0] in _WORD_VALUES and joined(k - 1, k) and joined(k, k + 1)):
                k += 1
            else:
                break
        half = (k + 2 < len(words) and [w[0] for w in words[k:k + 3]] == ["and", "a", "half"]
                and joined(k - 1, k) and joined(k, k + 1) and joined(k + 1, k + 2))
        if half:
            k += 3
        elif run == ["one"] and words[i][0] == "one":
            before = words[i - 1][0] if i > 0 and joined(i - 1, i) else None
            after = words[k][0] if k < len(words) and joined(k - 1, k) else None
            if before in _PRONOUN_ONE_AFTER or after in _PRONOUN_ONE_BEFORE:
                i = k
                continue

        total, current = 0, 0
        for word in run:
            if word in _WORD_VALUES:
                current += _WORD_VALUES[word]
            elif word == "hundred":
                current = (current or 1) * 100
            elif word == "dozen":
                current = (current or 1) * 12
            else:
                total += (current or 1) * _WORD_SCALES[word]
                current = 0
        value = total + current + (0.5 if half else 0)
        scaled = half or any(word in _WORD_SCALES for word in run)
        found.append((words[i][1], words[k - 1][2], float(value), scaled))
        i = k
    return found


def _in_code_word(text, start):
    """True when the digits at `start` are glued to letters that make
    the word a code rather than a figure -- "v1", "rf_v1", "Q4", "B2B"
    (see the note above). Digits with no letter or underscore right
    before them are never in one."""
    if start == 0 or not (text[start - 1].isalpha() or text[start - 1] == "_"):
        return False
    left, right = start, start
    while left > 0 and (text[left - 1].isalnum() or text[left - 1] == "_"):
        left -= 1
    while right < len(text) and (text[right].isalnum() or text[right] == "_"):
        right += 1
    word = text[left:right]
    return "_" in word or _CODE_WORD_RE.fullmatch(word) is not None


def _numbers_in(text):
    """[_Figure(value, small, percent, written), ...] for every number in
    `text`, in reading order: digits ("8.2", "61,020", "500k", "₱3.4m",
    "1.5 million") and words ("six", "twenty-five", "a dozen"). A peso
    prefix in any case -- "PHP500", "Php2,400,000", "P500" -- is read as
    ₱, so a currency prefix glued to the figure cannot hide it from the
    check; nor can a letter ("x25"), unless the word is a code ("rf_v1",
    "Q1")."""
    text = str(text or "")
    text = _PESO_PREFIX_RE.sub("₱", text)
    text = _DENOMINATOR_RE.sub(" ", text)
    found = []
    for match in _NUMBER_RE.finditer(text):
        if _in_code_word(text, match.start()):
            continue
        digits, suffix = match.group(1), (match.group(2) or "").strip().lower()
        value = float(digits.replace(",", "")) * _MAGNITUDES.get(suffix, 1)
        small = not suffix and "." not in digits and value <= _SMALL_INTEGER
        found.append((match.start(), match.end(), value, small, match.group(0)))
    # The scale word of "1.5 million" is already part of that figure;
    # read on its own as a word it would be a second, phantom million.
    digit_spans = [(row[0], row[1]) for row in found]
    for start, end, value, scaled in _spelled_numbers(text):
        if any(start < span_end and span_start < end for span_start, span_end in digit_spans):
            continue
        small = not scaled and value.is_integer() and value <= _SMALL_INTEGER
        found.append((start, end, value, small, text[start:end]))
    found.sort(key=lambda row: row[0])
    return [_Figure(value, small, _PERCENT_RE.match(text, end) is not None, written)
            for _start, end, value, small, written in found]


# Payload figures llm_service._model_output_prompt never prints, by path
# from the context root. They are the model's own and true, but the LLM
# has not seen them, so matching one can only be an accident -- see the
# note above. (The scorecard_index equals the printed viability_index on
# the formula path anyway, and there the components' points reach the
# prompt as the drivers.)
_UNSHOWN_PAYLOAD = frozenset({
    ("forecast", "components"),
    ("forecast", "plan", "scorecard_index"),
    ("forecast", "financials", "capital_adequacy"),
    ("forecast", "inputs", "residents_per_business"),
})
# The same holds for the sub-category analysis, which rides in the
# context whole: llm_service._plan_detail_prompt prints only its
# direct-competitor count (with its label and source), and the two
# saturation figures it quotes beside it are the context's own. The
# adjusted competitor count, the expected share, the density ratio, the
# industry-level viability score and the rest are never shown -- yet on
# any plan with a sub-category they would ground "break even in 4
# months" or "an index of 36". So the analysis is skipped whole and its
# direct_count added back by name (_grounding_numbers).
_UNSHOWN_ANALYSIS = frozenset({("subcategory_analysis",)})
# ...and the pricing figures, on a plan with no price list: the prompt
# then prints "No price list" instead of the pricing line, so the demand
# ceiling (and the zeros beside it) never reach the LLM either.
_PRICING_PAYLOAD = frozenset({
    ("forecast", "inputs", "average_price"),
    ("forecast", "financials", "gross_margin"),
    ("forecast", "financials", "required_daily_sales"),
    ("forecast", "financials", "daily_sales_ceiling"),
})


def _prices_are_shown(forecast):
    """True when the plan has a price list the model could read -- the
    same test the explanation and llm_service's prompt use to decide
    whether to print the pricing line at all."""
    inputs = forecast.get("inputs") or {}
    financials = forecast.get("financials") or {}
    return int(_number(inputs.get("priced_item_count"), 0) or 0) > 0 and \
        (_number(financials.get("required_daily_sales"), 0.0) or 0.0) > 0


def _collect_numbers(value, out, path=(), skip=_UNSHOWN_PAYLOAD):
    if path in skip or isinstance(value, bool) or value is None:
        return
    if isinstance(value, numbers.Number):
        out.add(abs(float(value)))
    elif isinstance(value, str):
        for figure in _numbers_in(value):
            out.add(figure.value)
    elif isinstance(value, dict):
        for key, item in value.items():
            _collect_numbers(item, out, path + (key,), skip)
    elif isinstance(value, (list, tuple, set)):
        for item in value:
            _collect_numbers(item, out, path, skip)


def _grounding_numbers(context):
    """(plain, scaled, percents) -- the figures an explanation may quote:

      plain    every number the prompt shows: the context and the
               payload inside it as they stand, less _UNSHOWN_PAYLOAD
               (and less _PRICING_PAYLOAD when there is no price list),
               and of the sub-category analysis only its direct
               competitor count (_UNSHOWN_ANALYSIS);
      scaled   the viability in its other scale (score x10, index /10).
               The VIABILITY only -- the one place two scales genuinely
               exist -- and only the plan's, the one the prompt prints.
               Applied to everything it would wave through nonsense:
               "30 months" would pass because the plan has 3 employees;
      percents the gross margin as the percentage the prompt prints it
               as (0.4 -> 40), for numbers written with a percent sign --
               and only when the pricing line that prints it is shown.

    Small integers are matched against `plain` alone (plus `percents`
    when written as one) -- see _matches."""
    forecast = _forecast(context) or {}
    prices_shown = bool(forecast) and _prices_are_shown(forecast)
    plain = set()
    skip = _UNSHOWN_PAYLOAD | _UNSHOWN_ANALYSIS
    _collect_numbers(context, plain, skip=skip if prices_shown else skip | _PRICING_PAYLOAD)
    analysis = context.get("subcategory_analysis")
    if isinstance(analysis, dict) and _number(analysis.get("direct_count")) is not None:
        plain.add(abs(_number(analysis.get("direct_count"))))

    plan = forecast.get("plan") or {}
    scaled = set()
    for score in (plan.get("viability_score"), context.get("viability_score")):
        if _number(score) is not None:
            scaled.add(abs(_number(score)) * 10)
    if _number(plan.get("viability_index")) is not None:
        scaled.add(abs(_number(plan.get("viability_index"))) / 10)

    percents = set()
    margin = _number((forecast.get("financials") or {}).get("gross_margin"))
    if margin is not None and prices_shown:
        percents.add(round(abs(margin) * 100, 1))
    return plain, scaled, percents


def _matches(figure, allowed):
    plain, scaled, percents = allowed
    value = abs(figure.value)
    if figure.small:
        pool = (plain | percents) if figure.percent else plain
        return any(abs(value - a) <= 0.5 for a in pool)
    pool = plain | scaled | (percents if figure.percent else set())
    return any(abs(value - a) <= 0.6 or abs(value - a) <= 0.02 * a for a in pool)


def ungrounded_numbers(text, context):
    """The numbers in `text`, as written, that match nothing in the
    context's payload or inputs (see the note above for what "match"
    allows). An empty list means the text is grounded."""
    allowed = _grounding_numbers(context)
    return [figure.written.strip() for figure in _numbers_in(text) if not _matches(figure, allowed)]


def _choose_explanation(llm_text, llm_generated_by, rule_explanation, context):
    """The LLM's explanation when it is present and grounded, else the
    rule-based one. Only ever an explanation of a payload: with no
    forecast in the context there is nothing to transcribe, and anything
    the LLM wrote anyway is ignored."""
    if _forecast(context) is None:
        return None
    text = " ".join(str(llm_text or "").split())
    if not text:
        return rule_explanation
    invented = ungrounded_numbers(text, context)
    if invented or len(text) > TRANSCRIPT_MAX_CHARS:
        try:
            from flask import current_app

            current_app.logger.info(
                "LLM forecast transcript discarded (%s); asking for a dedicated transcript, else the "
                "rule-based model summary stands",
                f"numbers not in the model output: {', '.join(invented)}" if invented else "too long",
            )
        except Exception:  # pragma: no cover - no app context
            pass
        return rule_explanation
    return {"text": text, "generated_by": llm_generated_by}


# ---------------------------------------------------------------------
# 2c. Checking a DEDICATED transcript (llm_service.transcribe_forecast)
# ---------------------------------------------------------------------
# The dedicated call shows Gemini more than the one-call prompt does --
# the seven scorecard parts, the capital adequacy, the residents per
# business -- so its transcript is checked against a different pool: the
# figures in the very block it was shown, read with the same _numbers_in
# and matched with the same _matches as above. Nothing it was not shown
# can ground it; everything it was shown can.

def transcript_allowed_figures(lines, forecast):
    """(plain, scaled, percents) for _matches, from the FORECAST
    COMPUTATION block's lines -- [(text, percent_only), ...]. A figure
    on a percent_only line (the gross margin, shown only as "40%")
    grounds only a number written as a percentage, exactly as the margin
    does in _grounding_numbers; every other figure grounds it written
    either way. `scaled` is the viability in its other scale."""
    plain, percents = set(), set()
    for text, percent_only in lines:
        for figure in _numbers_in(text):
            (percents if percent_only else plain).add(abs(figure.value))
    plan = (forecast or {}).get("plan") or {}
    scaled = set()
    if _number(plan.get("viability_score")) is not None:
        scaled.add(abs(_number(plan.get("viability_score"))) * 10)
    if _number(plan.get("viability_index")) is not None:
        scaled.add(abs(_number(plan.get("viability_index"))) / 10)
    return plain, scaled, percents


def _sentences(paragraph):
    """A paragraph's sentences: split after . ! or ? where the next one
    starts with a capital (or ₱), so "vs. running costs", "6.1/10" and
    "₱61,020" stay whole."""
    parts = re.split(r"(?<=[.!?])\s+(?=[\"'“(]?[A-Z₱])", str(paragraph or "").strip())
    return [part.strip() for part in parts if part.strip()]


def _paragraphs(text):
    return [p for p in re.split(r"\n\s*\n", str(text or "")) if p.strip()]


def states_viability(text, forecast):
    """True when some sentence that talks about viability ("viability",
    "viable") quotes the plan's own figure -- the score (6.1, or 6 out of
    10) or the index (61.3, or 61 out of 100). A transcript that has lost
    the verdict is not a transcript of this forecast."""
    plan = (forecast or {}).get("plan") or {}
    score, index = _number(plan.get("viability_score")), _number(plan.get("viability_index"))
    for paragraph in _paragraphs(text):
        for sentence in _sentences(paragraph):
            if not re.search(r"viab", sentence, re.I):
                continue
            for figure in _numbers_in(sentence):
                value = abs(figure.value)
                if (score is not None and abs(value - score) < 0.5) or \
                        (index is not None and abs(value - index) < 1.0):
                    return True
    return False


def review_transcript(text, allowed, forecast):
    """Everything wrong with a transcript, as a dict: "ungrounded" (the
    figures, as written, that match nothing in `allowed`), "too_long",
    "sentences" (how many), "states_viability", and "ok" -- True only
    when there is nothing wrong at all."""
    text = str(text or "")
    ungrounded = [figure.written.strip() for figure in _numbers_in(text) if not _matches(figure, allowed)]
    count = sum(len(_sentences(p)) for p in _paragraphs(text))
    review = {
        "ungrounded": ungrounded,
        "too_long": len(text) > TRANSCRIPT_MAX_CHARS,
        "sentences": count,
        "states_viability": states_viability(text, forecast),
    }
    review["ok"] = (not ungrounded and not review["too_long"] and count >= TRANSCRIPT_MIN_SENTENCES
                    and review["states_viability"])
    return review


def transcript_feedback(review):
    """What the retry is told, in the model's terms: the offending
    figures exactly as it wrote them, and anything else that was wrong."""
    problems = []
    if review.get("ungrounded"):
        problems.append("It quoted figures that are not in the FORECAST COMPUTATION: "
                        + "; ".join(dict.fromkeys(review["ungrounded"])) + ".")
    if review.get("too_long"):
        problems.append("It was too long -- keep to 5-8 sentences.")
    if review.get("sentences", 0) < TRANSCRIPT_MIN_SENTENCES:
        problems.append("It was too short -- write 5-8 sentences.")
    if not review.get("states_viability"):
        problems.append("It did not state the plan's viability score as given.")
    return " ".join(problems) or "It did not meet the rules."


def prune_transcript(text, allowed, forecast):
    """The transcript with every sentence that quotes an unverifiable
    figure dropped -- {"text", "kept", "dropped"} -- or None when what is
    left is no longer a transcript (fewer than TRANSCRIPT_MIN_SENTENCES
    sentences, the viability no longer stated, or still too long).

    Whole sentences go, never single figures: "break-even in ₱ months"
    with the number cut out would be worse than the sentence missing.
    Paragraph breaks are kept."""
    kept_paragraphs, kept, dropped = [], 0, 0
    for paragraph in _paragraphs(text):
        survivors = []
        for sentence in _sentences(paragraph):
            if any(not _matches(figure, allowed) for figure in _numbers_in(sentence)):
                dropped += 1
            else:
                survivors.append(sentence)
        if survivors:
            kept += len(survivors)
            kept_paragraphs.append(" ".join(survivors))
    pruned = "\n\n".join(kept_paragraphs)
    if not review_transcript(pruned, allowed, forecast)["ok"]:
        return None
    return {"text": pruned, "kept": kept, "dropped": dropped}


def _rule_based_recommendation(context):
    headline, opportunity_type = _headline_and_type_for(context["cluster_label"])
    return {
        "headline": headline,
        "opportunity_type": opportunity_type,
        "summary": _summary_for(context),
        "reasons": _reasons_for(context),
        "risks": _risks_for(context),
        "generated_by": "rule_based",
        "subcategory_analysis": context.get("subcategory_analysis"),
        "innovation": _rule_based_innovation(context),
        "forecast": _forecast(context),
        "explanation": _rule_based_explanation(context),
        "competitor_insight": _rule_based_competitor_insight(context, _rule_based_innovation(context)),
    }


def llm_recommendations_enabled():
    """The ONE place that decides whether the LLM is asked to write.

    There used to be two answers to this question and only one of them
    was ever consulted. USE_LLM_RECOMMENDATIONS is documented in .env,
    in DEPLOYMENT.md and in render.yaml as the switch -- and it was
    read into Config and then never looked at. The real switch was a
    row in the system_settings table, reachable only through Admin >
    System Settings. Setting the environment variable on a host and
    watching nothing change is a genuinely baffling half hour, so:

      * If USE_LLM_RECOMMENDATIONS is set in the environment, it wins.
        An operator who has written the variable down in a deployment
        panel means it, and they may have no way to reach the admin UI
        on a fresh instance.
      * Otherwise the database setting decides, so the admin toggle
        keeps working exactly as before for anyone not setting the
        variable.

    Being explicit matters here: an UNSET variable must fall through to
    the database, while USE_LLM_RECOMMENDATIONS=false must actually
    turn the feature off rather than being indistinguishable from
    absent.
    """
    import os

    raw = os.environ.get("USE_LLM_RECOMMENDATIONS")
    if raw is not None and str(raw).strip() != "":
        return str(raw).strip().lower() in ("1", "true", "yes", "on")

    return SystemSetting.get_bool("use_llm_recommendations", False)


def build_recommendation(context):
    """Returns a structured recommendation dict -- {headline,
    opportunity_type, summary, reasons, risks, generated_by,
    subcategory_analysis, innovation, forecast, explanation} -- ready
    for serialize_recommendation() to store in
    forecast_result.recommendation.

    When use_llm_recommendations is on, asks the LLM -- Gemini first for
    this call, then the provider in LLM_PROVIDER, then the rest (see
    llm_service.generate_recommendation_json) -- for the wording and the
    forecast explanation; always falls back to the deterministic
    rule-based recommendation above if the LLM is off, unconfigured, or
    fails for any reason -- the page never breaks because of this.

    "forecast" is the trained model's payload from the context, on both
    paths: the LLM is asked to write ABOUT it and is never allowed to
    supply it. The LLM's transcript (stored as "explanation") replaces
    the rule-based model summary only when it passes the grounding check
    (ungrounded_numbers); its headline, summary, reasons and risks are
    used as before.

    WHEN THAT TRANSCRIPT IS MISSING OR REJECTED, the dedicated
    transcription call is asked before the model summary is settled for
    (llm_service.transcribe_forecast: the whole computation, Gemini
    first, one corrective retry, then sentence pruning). It is asked
    when the one call answered at all -- some provider is working -- or,
    if every provider failed it, when Gemini has a plausible key: the
    dedicated call's reply is far shorter, so it can succeed where the
    long one ran out of room. With no usable provider at all it is not
    asked, since nothing would be different the second time."""
    recommendation = _rule_based_recommendation(context)

    if llm_recommendations_enabled():
        from app.services import llm_service
        from app.services.llm_service import generate_recommendation_json

        with llm_service.ai_time_budget(AI_TIME_BUDGET_AT_FORECAST):
            llm_payload = generate_recommendation_json(context)
            if llm_payload:
                recommendation = _apply_llm_payload(recommendation, llm_payload, context)

            explanation = recommendation.get("explanation")
            if _forecast(context) is not None and not _is_ai(explanation) and \
                    (llm_payload or llm_service.gemini_transcription_available()):
                transcript = llm_service.transcribe_forecast(context)
                if transcript:
                    recommendation["explanation"] = transcript

        if _forecast(context) is not None and ai_text_pending(recommendation) and \
                isinstance(recommendation.get("explanation"), dict):
            # Gemini was just asked and failed for part of it. Stamp it
            # as mark_transcript_failed would, so the page that shows
            # this forecast waits TRANSCRIPT_RETRY_AFTER before asking
            # again -- and then upgrades what is still the template.
            recommendation["explanation"] = _stamped(recommendation["explanation"])

    return recommendation


def _is_ai(part):
    """True when a stored part (the recommendation, its explanation, its
    competitor insight) was written by an AI: generated_by "llm:...". """
    return isinstance(part, dict) and str(part.get("generated_by") or "").startswith("llm:")


def _stamped(explanation, now=None):
    return {**explanation,
            "transcript_failed_at": (now or datetime.now(timezone.utc)).isoformat(timespec="seconds"),
            "transcript_failed_version": TRANSCRIPT_REQUEST_VERSION}


def _apply_llm_payload(recommendation, llm_payload, context):
    """`recommendation` (the rule-based one, or a stored one) with the
    LLM's answer from generate_recommendation_json merged in: its
    headline, opportunity type, summary, reasons and risks; its read of
    the owner's idea; its competitor insight and its transcript when they
    pass the number check. What is a measurement -- the sub-category
    analysis, the trained model's payload -- always comes from the
    context, never from the LLM."""
    rule_innovation = recommendation.get("innovation") or _rule_based_innovation(context)
    rule_explanation = recommendation.get("explanation")
    llm_payload = dict(llm_payload)
    llm_innovation = llm_payload.pop("innovation", None)
    llm_explanation = llm_payload.pop("explanation", None)
    llm_competitor_insight = llm_payload.pop("competitor_insight", None)
    llm_model = llm_payload.pop("model", None)
    llm_payload.pop("forecast", None)
    merged = dict(llm_payload)
    # The sub-category figures are measurements, never the model's
    # words -- they always come from the context.
    merged["subcategory_analysis"] = context.get("subcategory_analysis")
    # Likewise the forecast: the trained model's output, never anything
    # the LLM said about it.
    merged["forecast"] = _forecast(context)
    # "llm:gemini:gemini-3.8-flash" -- the provider AND the exact model,
    # because "explained by Gemini" should be checkable.
    writer = llm_payload.get("generated_by") or "llm"
    if llm_model:
        writer = f"{writer}:{llm_model}"
    if _is_ai(rule_explanation):
        merged["explanation"] = rule_explanation  # already transcribed: kept
    else:
        merged["explanation"] = _choose_explanation(llm_explanation, writer, rule_explanation, context)
    has_idea = bool(rule_innovation.get("has_idea"))
    if llm_innovation and (llm_innovation["novelty"] if has_idea else llm_innovation["summary"]) \
            and not ungrounded_numbers(llm_innovation["summary"], context):
        # The LLM judges the idea -- or, with none on the plan yet, says
        # what could set the business apart; the differentiation need
        # stays the one read from the saturation model.
        merged["innovation"] = {
            **rule_innovation,
            "novelty": llm_innovation["novelty"] if has_idea else None,
            "summary": llm_innovation["summary"] or rule_innovation["summary"],
            "suggestions": llm_innovation["suggestions"] or rule_innovation["suggestions"],
            "generated_by": llm_payload.get("generated_by"),
        }
    else:
        merged["innovation"] = rule_innovation
    # Judged AFTER the innovation, so the rule-based fallback can name the
    # novelty the AI just rated.
    merged["competitor_insight"] = _choose_competitor_insight(
        llm_competitor_insight, writer,
        _rule_based_competitor_insight(context, merged["innovation"]), context,
    )
    return merged


def ai_text_pending(rec):
    """Which of a forecast's texts are still the template rather than the
    AI's -- a set of "recommendation" (the headline, summary, reasons,
    risks and the rest written with them) and "transcript" (the forecast
    transcript). Empty for a forecast with no trained-model payload: it
    has nothing an upgrade could write about (it is re-run instead)."""
    if not isinstance(rec, dict) or not isinstance(rec.get("forecast"), dict):
        return set()
    pending = set()
    if not str(rec.get("generated_by") or "").startswith("llm:"):
        pending.add("recommendation")
    explanation = rec.get("explanation")
    if isinstance(explanation, dict) and explanation.get("text") and not _is_ai(explanation):
        pending.add("transcript")
    return pending


def upgrade_ai_text(forecast_row, sme_profile):
    """Ask the AI for whatever of a STORED forecast is still the template
    -- see ai_text_pending -- and return the outcome, or None when the
    row has no payload to write about:

        {"raw": the recommendation JSON to store,
         "changed": the parts the AI wrote just now,
         "pending": the parts still the template (the failure is then
                    stamped, see transcript_failed_recently)}

    The recommendation is asked for first: one call writes it AND a
    transcript (generate_recommendation_json). Whatever transcript is
    still missing after it is asked for on its own (transcribe_forecast).
    Nothing is re-scored -- the context is the stored payload's
    (transcript_context) -- and the payload, the sub-category analysis
    and every key not written here are stored back exactly as read."""
    from app.services import llm_service

    stored = stored_recommendation(forecast_row.recommendation)
    context = transcript_context(forecast_row, sme_profile)
    if stored is None or context is None:
        return None
    rec = parse_recommendation(forecast_row.recommendation)
    pending = ai_text_pending(rec)
    changed = set()
    with llm_service.ai_time_budget(AI_TIME_BUDGET_FOR_UPGRADE):
        if "recommendation" in pending:
            llm_payload = llm_service.generate_recommendation_json(context)
            if llm_payload:
                base = {**rec, "innovation": rec.get("innovation") or _rule_based_innovation(context)}
                merged = _apply_llm_payload(base, llm_payload, context)
                for key in ("headline", "opportunity_type", "summary", "reasons", "risks", "generated_by",
                            "innovation", "competitor_insight"):
                    stored[key] = merged.get(key)
                changed.add("recommendation")
                if "transcript" in pending and _is_ai(merged.get("explanation")):
                    stored["explanation"] = merged["explanation"]
                    changed.add("transcript")
        if "transcript" in pending and "transcript" not in changed:
            transcript = llm_service.transcribe_forecast(context)
            if transcript:
                stored["explanation"] = {"text": transcript["text"], "generated_by": transcript["generated_by"]}
                changed.add("transcript")
    still = pending - changed
    if still and isinstance(stored.get("explanation"), dict):
        stored["explanation"] = _stamped(stored["explanation"])
    elif not still and isinstance(stored.get("explanation"), dict):
        # Done: the retry stamp of an earlier failure goes with it.
        stored["explanation"] = {key: value for key, value in stored["explanation"].items()
                                 if key not in ("transcript_failed_at", "transcript_failed_version")}
    return {"raw": json.dumps(stored, ensure_ascii=False), "changed": changed, "pending": still}


# ---------------------------------------------------------------------
# 3. Storage -- JSON-in-a-TEXT-column, with backward-compatible parsing
#    for rows written before this change existed.
# ---------------------------------------------------------------------

def serialize_recommendation(recommendation):
    """Ready to store directly in forecast_result.recommendation."""
    return json.dumps(
        {key: recommendation.get(key) for key in _KEYS},
        ensure_ascii=False,
    )


def _empty_recommendation():
    return {
        "headline": "",
        "opportunity_type": "Moderate Opportunity",
        "summary": "No recommendation available yet.",
        "reasons": [],
        "risks": [],
        "generated_by": "none",
        "subcategory_analysis": None,
        "innovation": None,
        "forecast": None,
        "explanation": None,
        "competitor_insight": None,
    }


def _parse_competitor_insight(payload):
    """The stored insight, or -- for a forecast written before insights
    existed -- the rule-based one rebuilt from what that row DID store,
    so the Planning and Recommendations pages never show a gap."""
    value = payload.get("competitor_insight")
    if isinstance(value, dict) and value.get("short"):
        return value
    forecast = payload.get("forecast") if isinstance(payload.get("forecast"), dict) else {}
    market = forecast.get("market") or {}
    inputs = forecast.get("inputs") or {}
    analysis = payload.get("subcategory_analysis")
    analysis = analysis if isinstance(analysis, dict) else None
    if not analysis and not market:
        return None
    innovation = payload.get("innovation")
    return competitor_insight_from(
        analysis, market.get("competitor_count"), inputs.get("industry_type"),
        inputs.get("location"), innovation if isinstance(innovation, dict) else None,
    )


def _parse_explanation(value):
    """{"text", "generated_by"} from storage -- plus "transcript_failed_at"
    when an upgrade to a Gemini transcript last failed (see
    mark_transcript_failed) -- or None when the row has no usable
    transcript (every row written before the two-stage model)."""
    if not isinstance(value, dict):
        return None
    text = str(value.get("text") or "").strip()
    if not text:
        return None
    parsed = {"text": text, "generated_by": str(value.get("generated_by") or RULE_BASED_EXPLANATION)}
    if isinstance(value.get("transcript_failed_at"), str):
        parsed["transcript_failed_at"] = value["transcript_failed_at"]
        parsed["transcript_failed_version"] = value.get("transcript_failed_version")
    return parsed


# ---------------------------------------------------------------------
# 3b. Upgrading a STORED forecast's transcript
# ---------------------------------------------------------------------
# A forecast stored with the rule-based model summary -- made while no
# Gemini key was configured, or before the transcript existed -- is
# upgraded after the fact, from the page, without blocking its render:
# the page shows the summary with a "Gemini is transcribing..." note,
# and static/js/forecast_transcript.js asks
# POST /api/forecasts/<id>/transcript (api_controller). Nothing is
# re-scored: the context is rebuilt from the stored payload and the
# plan, and only the stored "explanation" changes.

def _utc(stamp):
    """An ISO timestamp as an aware UTC datetime, or None. A naive one is
    read as UTC (that is how every timestamp here is written)."""
    try:
        when = datetime.fromisoformat(str(stamp).strip().replace("Z", "+00:00"))
    except (TypeError, ValueError):
        return None
    return when if when.tzinfo else when.replace(tzinfo=timezone.utc)


def transcript_failed_recently(explanation, now=None):
    """True while a failed upgrade is younger than TRANSCRIPT_RETRY_AFTER
    AND was made with the current Gemini request -- a stamp left by an
    older request version is ignored (see TRANSCRIPT_REQUEST_VERSION)."""
    if not isinstance(explanation, dict):
        return False
    if explanation.get("transcript_failed_version") != TRANSCRIPT_REQUEST_VERSION:
        return False
    when = _utc(explanation.get("transcript_failed_at"))
    if when is None:
        return False
    now = now or datetime.now(timezone.utc)
    return now - when < TRANSCRIPT_RETRY_AFTER


def transcript_upgrade_due(rec, now=None):
    """Whether the page should ask Gemini to write what is still the
    template in this parsed recommendation (parse_recommendation's
    dict): it carries the model's payload, its recommendation or its
    transcript is still rule-based (ai_text_pending), no upgrade failed
    in the last TRANSCRIPT_RETRY_AFTER, and Gemini can plausibly be
    asked (llm_service.gemini_transcription_available -- the LLM switch
    on and a usable Gemini key). Registered as the template global
    `forecast_transcript_due` (api_controller), read by
    shared/_plan_insights.html. The cheap checks come first, so a page
    of AI-written forecasts never touches the key or the switch."""
    if not ai_text_pending(rec):
        return False
    explanation = rec.get("explanation")
    if not isinstance(explanation, dict) or not explanation.get("text"):
        return False
    if transcript_failed_recently(explanation, now):
        return False
    from app.services.llm_service import gemini_transcription_available

    return gemini_transcription_available()


def transcript_queue_due(rec, now=None):
    """Whether a plan's LATEST forecast should be queued for a Gemini
    transcript in the background (Planning and Home queue every plan,
    not only the one on screen). Either its transcript can be upgraded
    (transcript_upgrade_due), or it predates the plan model altogether
    -- no payload to transcribe -- and the endpoint re-runs the plan's
    forecast, which writes a transcript as it goes."""
    if transcript_upgrade_due(rec, now):
        return True
    if not isinstance(rec, dict) or isinstance(rec.get("forecast"), dict):
        return False
    from app.services.llm_service import gemini_transcription_available

    return gemini_transcription_available()


def stored_recommendation(raw_text):
    """forecast_result.recommendation as the dict it was stored as, or
    None for a legacy plain-text row or anything unreadable."""
    try:
        payload = json.loads(str(raw_text or ""))
    except (ValueError, TypeError):
        return None
    return payload if isinstance(payload, dict) else None


def store_transcript(raw_text, transcript):
    """The stored recommendation JSON with ONLY its "explanation"
    replaced by `transcript` ({"text", "generated_by"}). Every other key
    -- the payload, the headline, the reasons, anything a later version
    added -- is written back exactly as it was read; the retry stamp of
    an earlier failure goes with the summary it was attached to."""
    payload = stored_recommendation(raw_text)
    if payload is None:
        raise ValueError("not a stored JSON recommendation")
    payload["explanation"] = {"text": transcript["text"], "generated_by": transcript["generated_by"]}
    return json.dumps(payload, ensure_ascii=False)


def mark_transcript_failed(raw_text, now=None):
    """The stored recommendation JSON with explanation["transcript_failed_at"]
    set to now (ISO, UTC), so the page leaves this forecast alone for
    TRANSCRIPT_RETRY_AFTER. The model summary's text and everything else
    stay as they were."""
    payload = stored_recommendation(raw_text)
    if payload is None:
        raise ValueError("not a stored JSON recommendation")
    explanation = dict(payload.get("explanation") or {}) if isinstance(payload.get("explanation"), dict) else {}
    payload["explanation"] = _stamped(explanation, now)
    return json.dumps(payload, ensure_ascii=False)


def transcript_retry_in(explanation, now=None):
    """Whole seconds until a failed upgrade may be retried (0 when it may
    be now) -- what the page waits before asking again."""
    when = _utc((explanation or {}).get("transcript_failed_at")) if isinstance(explanation, dict) else None
    if when is None or not transcript_failed_recently(explanation, now):
        return 0
    now = now or datetime.now(timezone.utc)
    return max(1, int((when + TRANSCRIPT_RETRY_AFTER - now).total_seconds()) + 1)


def transcript_context(forecast_row, sme_profile):
    """The context transcribe_forecast needs, rebuilt for a STORED
    forecast -- from its stored payload and its plan, with no scoring.
    The market figures come from the payload (what the forecast actually
    said), the row's own columns standing in only where an older payload
    lacks one. None when the row has no payload to transcribe."""
    stored = parse_recommendation(forecast_row.recommendation)
    payload = stored.get("forecast")
    if not isinstance(payload, dict):
        return None
    market = payload.get("market") or {}
    plan = payload.get("plan") or {}
    inputs = payload.get("inputs") or {}
    saturation = _number(market.get("saturation_index"), _number(forecast_row.saturation_index, 0.0))
    scores = {
        "saturation_index": saturation,
        "industry_saturation_index": _number(market.get("industry_saturation_index"), saturation),
        "cluster_label": market.get("cluster_label") or forecast_row.cluster_label,
        "viability_score": _number(plan.get("viability_score"), _number(forecast_row.viability_score, 0.0)),
        "confidence_level": _number(forecast_row.confidence_level,
                                    _number(plan.get("confidence"), _number(market.get("confidence"), 0.0))),
        "competitor_count": int(_number(market.get("competitor_count"), 0) or 0),
    }
    return build_recommendation_context(
        sme_profile, scores,
        population=_number(inputs.get("population"), 0) or 0,
        subcategory_analysis=stored.get("subcategory_analysis"),
        plan_forecast=payload,
    )


def _opportunity_type_from_headline(headline):
    upper = (headline or "").upper()
    if "HIGH SATURATION" in upper:
        return "High Saturation"
    if "MODERATE" in upper:
        return "Moderate Opportunity"
    if "HIGH OPPORTUNITY" in upper:
        return "High Opportunity"
    return "Moderate Opportunity"


def parse_recommendation(raw_text):
    """Returns the structured dict every template expects, whether
    `raw_text` is one of THIS version's JSON-serialized
    recommendations, or a legacy plain-text row written by the old
    rule_based_text()/LLM plain-text generator this module used before
    this change (format: "<HEADLINE>\\n\\n<summary>\\n\\nWhy: r1; r2.
    \\n\\nConsiderations: c1; c2."). Never raises -- a value nobody can
    make sense of still returns a fully-shaped dict so every template
    field always has *something* to render."""
    if not raw_text or not str(raw_text).strip():
        return _empty_recommendation()

    text = str(raw_text).strip()

    if text.startswith("{"):
        try:
            payload = json.loads(text)
        except (ValueError, TypeError):
            payload = None
        if isinstance(payload, dict) and "headline" in payload:
            return {
                "headline": payload.get("headline") or "",
                "opportunity_type": payload.get("opportunity_type") or "Moderate Opportunity",
                "summary": payload.get("summary") or "",
                "reasons": [str(r) for r in (payload.get("reasons") or [])],
                "risks": [str(r) for r in (payload.get("risks") or [])],
                "generated_by": payload.get("generated_by") or "rule_based",
                # Absent on forecasts written before sub-categories and
                # the innovation read existed; templates check for None.
                "subcategory_analysis": payload.get("subcategory_analysis")
                if isinstance(payload.get("subcategory_analysis"), dict) else None,
                "innovation": payload.get("innovation")
                if isinstance(payload.get("innovation"), dict) else None,
                # Absent on forecasts written before the trained plan
                # model; the Home page regenerates those once.
                "forecast": payload.get("forecast")
                if isinstance(payload.get("forecast"), dict) else None,
                "explanation": _parse_explanation(payload.get("explanation")),
                "competitor_insight": _parse_competitor_insight(payload),
            }

    # Legacy plain-text fallback (pre-JSON format).
    headline = text.split("\n", 1)[0].strip()

    summary_match = re.search(r"\n\n(.*?)\n\nWhy:", text, re.DOTALL)
    summary = re.sub(r"\s+", " ", summary_match.group(1)).strip() if summary_match else ""

    why_match = re.search(r"Why:\s*(.*?)\.?\s*(?:\n\n|$)", text, re.DOTALL)
    reasons = [r.strip() for r in why_match.group(1).split(";") if r.strip()] if why_match else []

    considerations_match = re.search(r"Considerations:\s*(.*?)\.?\s*$", text, re.DOTALL)
    risks = [r.strip() for r in considerations_match.group(1).split(";") if r.strip()] if considerations_match else []

    return {
        "headline": headline,
        "opportunity_type": _opportunity_type_from_headline(headline),
        "summary": summary,
        "reasons": reasons,
        "risks": risks,
        "generated_by": "legacy",
        "subcategory_analysis": None,
        "innovation": None,
        "forecast": None,
        "explanation": None,
        "competitor_insight": None,
    }


# ---------------------------------------------------------------------
# 4. Small display-only helpers for the Recommendations page -- derived
#    from real numbers already on file, never fabricated ranges.
# ---------------------------------------------------------------------

def competition_level_label(competitor_count):
    count = int(competitor_count or 0)
    if count == 0:
        return f"Very Low ({count} competitors)"
    if count <= 2:
        return f"Low ({count} competitors)"
    if count <= 6:
        return f"Moderate ({count} competitors)"
    return f"High ({count} competitors)"
