"""
tests/test_gemini_everywhere.py
---------------------------------
"Make all the incoming new plan ... the gemini transcript work well",
"the recommendation should also generated by Gemini AI", and "fix all
the new creating plan, not just the existed plans". One plan of three
came back from Gemini and the others kept the template, because a
single busy answer from Google (HTTP 429/503) or a slow one (the
timeout) was the end of it. These tests pin what replaced that:

  * a temporary failure is SENT AGAIN -- after the wait Google asks for,
    or a short backoff -- and a permanent one (a bad key, a spent daily
    quota) is not; every send stays inside the request's time budget;
  * a NEW plan comes out of the forecast run written by Gemini -- the
    recommendation, the competitor insight, the innovation read and the
    transcript -- even when Gemini is busy at first and its transcript
    drafts quote a figure the model never produced (it is then asked to
    restate the model's own summary);
  * a stored forecast whose recommendation is still the template is
    upgraded by the page in the background like its transcript, and the
    page repaints those parts in place;
  * a competitor insight with one bad sentence keeps the good ones.

No network: requests.post and the generators are faked.

Run with:
    pytest tests/test_gemini_everywhere.py -v
"""

import json
import os
import re

import pytest

from app import create_app
from app.extensions import db
from app.models import ForecastResult, SmeProfile, SystemSetting, User
from app.services import llm_service
from app.services import recommendation_service as rec_service

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
MODEL = "gemini-3.8-flash"


@pytest.fixture
def app(monkeypatch):
    monkeypatch.delenv("USE_LLM_RECOMMENDATIONS", raising=False)
    app = create_app("testing")
    with app.app_context():
        db.create_all()
        SystemSetting.ensure_defaults()
        app.config.update(GEMINI_API_KEY="", OPENAI_API_KEY="", ANTHROPIC_API_KEY="", GEMINI_MODEL=MODEL)
        yield app
        db.session.remove()
        db.drop_all()


@pytest.fixture(autouse=True)
def _clean(monkeypatch):
    llm_service.reset_client_cache()
    slept = []
    monkeypatch.setattr(llm_service, "_sleep", slept.append)
    yield slept
    llm_service.reset_client_cache()


def _gemini_on(app, monkeypatch):
    monkeypatch.setenv("USE_LLM_RECOMMENDATIONS", "true")
    app.config.update(GEMINI_API_KEY="AQ.Ab_test_everywhere_key", LLM_PROVIDER="gemini")


class _Response:
    def __init__(self, status_code, text="", payload=None, headers=None):
        self.status_code = status_code
        self.text = text if text or payload is None else json.dumps(payload)
        self._payload = payload
        self.headers = headers or {}

    def json(self):
        return self._payload if self._payload is not None else json.loads(self.text)


def _ok(text):
    return _Response(200, payload={"candidates": [{"content": {"parts": [{"text": text}]}}]})


def _busy(status=503, delay=None):
    body = {"error": {"code": status, "status": "UNAVAILABLE" if status == 503 else "RESOURCE_EXHAUSTED",
                      "message": "The model is overloaded."}}
    if delay is not None:
        body["error"]["details"] = [{"@type": "type.googleapis.com/google.rpc.RetryInfo", "retryDelay": delay}]
    return _Response(status, text=json.dumps(body))


def _fake_post(monkeypatch, answer):
    """requests.post replaced by `answer(prompt, n)` -> a response (n is
    the 1-based count of sends so far); returns the prompts sent."""
    import requests

    prompts = []

    def post(url, headers=None, json=None, timeout=None):
        prompt = json["contents"][0]["parts"][0]["text"]
        prompts.append(prompt)
        result = answer(prompt, len(prompts))
        if isinstance(result, Exception):
            raise result
        return result

    monkeypatch.setattr(requests, "post", post)
    return prompts


# ---------------------------------------------------------------------
# 1. The send: temporary failures are retried, permanent ones are not
# ---------------------------------------------------------------------

@pytest.mark.parametrize("first", [_busy(503), _busy(429), _busy(500)])
def test_a_busy_answer_is_sent_again(app, monkeypatch, first):
    with app.app_context():
        _gemini_on(app, monkeypatch)
        prompts = _fake_post(monkeypatch, lambda prompt, n: first if n == 1 else _ok('{"ok": true}'))
        assert llm_service._generate_with_gemini("hi") == '{"ok": true}'
    assert len(prompts) == 2


def test_a_timeout_is_sent_again(app, monkeypatch):
    import requests

    with app.app_context():
        _gemini_on(app, monkeypatch)
        prompts = _fake_post(monkeypatch, lambda prompt, n: requests.exceptions.ReadTimeout("slow")
                             if n == 1 else _ok('{"ok": true}'))
        assert llm_service._generate_with_gemini("hi") == '{"ok": true}'
    assert len(prompts) == 2


def test_the_wait_google_asks_for_is_honoured(app, monkeypatch, _clean):
    with app.app_context():
        _gemini_on(app, monkeypatch)
        _fake_post(monkeypatch, lambda prompt, n: _busy(429, delay="7s") if n == 1 else _ok('{"ok": true}'))
        assert llm_service._generate_with_gemini("hi") == '{"ok": true}'
    assert _clean == [7.0]


def test_a_spent_daily_quota_is_not_waited_out(app, monkeypatch, _clean):
    with app.app_context():
        _gemini_on(app, monkeypatch)
        prompts = _fake_post(monkeypatch, lambda prompt, n: _busy(429, delay="3600s"))
        assert llm_service._generate_with_gemini("hi") is None
        failure = llm_service.last_failure()
    assert len(prompts) == 1 and _clean == []
    assert "429" in failure["detail"]


@pytest.mark.parametrize("status", [400, 401, 403, 404])
def test_a_permanent_failure_is_not_sent_again(app, monkeypatch, status):
    with app.app_context():
        _gemini_on(app, monkeypatch)
        prompts = _fake_post(monkeypatch, lambda prompt, n: _Response(status, text='{"error": "no"}'))
        assert llm_service._generate_with_gemini("hi") is None
    assert len(prompts) == 1


def test_sends_stop_at_the_attempt_limit_and_say_how_many(app, monkeypatch):
    with app.app_context():
        _gemini_on(app, monkeypatch)
        prompts = _fake_post(monkeypatch, lambda prompt, n: _busy(503))
        assert llm_service._generate_with_gemini("hi") is None
        detail = llm_service.last_failure()["detail"]
    assert len(prompts) == llm_service.GEMINI_ATTEMPTS
    assert "503" in detail and f"after {llm_service.GEMINI_ATTEMPTS} sends" in detail


def test_no_send_starts_once_the_time_budget_is_spent(app, monkeypatch):
    import time as time_module

    clock = {"now": 500.0}
    monkeypatch.setattr(time_module, "monotonic", lambda: clock["now"])
    with app.app_context():
        _gemini_on(app, monkeypatch)

        def answer(prompt, n):
            clock["now"] += 35  # each busy answer takes 35 s
            return _busy(503)

        prompts = _fake_post(monkeypatch, answer)
        with llm_service.ai_time_budget(40):
            assert llm_service._generate_with_gemini("hi") is None
    assert len(prompts) == 1, "5 s left is too little for another send"


def test_one_call_never_holds_a_page_past_its_own_ceiling(app, monkeypatch):
    """Outside any budget (the Recommendations page's barangay cards, the
    alerts) a call still stops retrying at GEMINI_CALL_BUDGET_SECONDS."""
    import requests
    import time as time_module

    clock = {"now": 100.0}
    monkeypatch.setattr(time_module, "monotonic", lambda: clock["now"])
    with app.app_context():
        _gemini_on(app, monkeypatch)
        timeouts = []

        def answer(prompt, n):
            clock["now"] += llm_service.GEMINI_TIMEOUT_SECONDS
            timeouts.append(n)
            return requests.exceptions.ReadTimeout("slow")

        _fake_post(monkeypatch, answer)
        started = clock["now"]
        assert llm_service._generate_with_gemini("hi") is None
    assert len(timeouts) == 2
    assert clock["now"] - started <= llm_service.GEMINI_CALL_BUDGET_SECONDS + llm_service.GEMINI_TIMEOUT_SECONDS


# ---------------------------------------------------------------------
# 2. A NEW plan: everything Gemini, even when Gemini struggles at first
# ---------------------------------------------------------------------

def _user(email, role="SME"):
    user = User(name=email.split("@")[0], email=email, role=role)
    user.set_password("password123")
    db.session.add(user)
    db.session.commit()
    return user


def _client(app, email):
    client = app.test_client()
    client.post("/login", data={"email": email, "password": "password123"}, follow_redirects=True)
    return client


ONE_CALL = {
    "headline": "MODERATE OPPORTUNITY -- a preschool can still win here with a clear niche.",
    "opportunity_type": "Moderate Opportunity",
    "summary": "Your preschool plan is workable in Balete if you stand out from the schools already there.",
    "reasons": ["Your capital covers the ramp-up.", "Parents nearby need trusted early learning."],
    "risks": ["Several preschools already trade here.", "No price list yet, so fees are unchecked."],
    "competitor_insight": {
        "short": "Preschools already trade in Balete, but a clear focus on manners can still win parents.",
        "detail": "Preschools already trade here. A clear focus on good manners sets this plan apart. "
                  "Show parents that focus from the first visit.",
    },
    "innovation": {"summary": "A clear point of difference would help this preschool stand out here.",
                   "suggestions": ["Offer a manners-first curriculum", "Run short parent workshops"]},
}


def _model_summary_in(prompt):
    return prompt.split("MODEL SUMMARY\n", 1)[1].split("\n\nRewrite the MODEL SUMMARY", 1)[0]


def _new_plan(app):
    owner = _user("owner@everywhere.test")
    plan = SmeProfile(user_id=owner.user_id, business_name="Little Steps", industry_type="Education",
                      subcategory="preschool", location="Balete", business_stage="startup",
                      startup_capital=800000, employee_count=2,
                      product_offering="Teach good manners and conduct for the kids 2-3 years old")
    db.session.add(plan)
    db.session.commit()
    return plan


def test_a_new_plan_is_written_by_gemini_even_when_it_is_busy_at_first(app, monkeypatch):
    """The one call meets a 503 and is sent again; its answer carries no
    transcript, and every draft of the dedicated transcript quotes a
    figure the model never produced -- so Gemini is finally handed the
    model's own summary to restate. The plan still opens with nothing
    but Gemini's text."""
    from app.services.forecasting_service import generate_forecast_for_profile

    def answer(prompt, n):
        if '"headline"' in prompt:
            return _busy(503) if n == 1 else _ok(json.dumps(ONE_CALL))
        if "MODEL SUMMARY" in prompt:
            return _ok(json.dumps({"transcript": _model_summary_in(prompt)}))
        return _ok(json.dumps({"transcript": (
            "The plan scores well and earns ₱9,876,543 a year. Its viability is set by the model. "
            "Fees of ₱4,321 a month suit Balete. Break-even comes in 2 weeks.")}))

    with app.app_context():
        _gemini_on(app, monkeypatch)
        prompts = _fake_post(monkeypatch, answer)
        row = generate_forecast_for_profile(_new_plan(app))
        rec = rec_service.parse_recommendation(row.recommendation)

    assert rec["generated_by"] == "llm:gemini"
    assert rec["headline"] == ONE_CALL["headline"] and rec["reasons"] == ONE_CALL["reasons"]
    assert rec["explanation"]["generated_by"] == f"llm:gemini:{MODEL}"
    assert "9,876,543" not in rec["explanation"]["text"]
    assert rec["competitor_insight"]["generated_by"].startswith("llm:gemini")
    assert rec["innovation"]["generated_by"] == "llm:gemini" and rec["innovation"]["novelty"] is None
    assert rec["innovation"]["summary"] == ONE_CALL["innovation"]["summary"]
    assert rec_service.ai_text_pending(rec) == set(), "nothing is left for the page to upgrade"
    assert "transcript_failed_at" not in json.loads(row.recommendation)["explanation"]
    assert any("MODEL SUMMARY" in prompt for prompt in prompts), "the restatement was asked for"


def test_a_new_plan_that_gemini_could_not_write_is_stamped_for_the_page(app, monkeypatch):
    from app.services.forecasting_service import generate_forecast_for_profile

    with app.app_context():
        _gemini_on(app, monkeypatch)
        _fake_post(monkeypatch, lambda prompt, n: _busy(503))
        row = generate_forecast_for_profile(_new_plan(app))
        rec = rec_service.parse_recommendation(row.recommendation)
    assert rec_service.ai_text_pending(rec) == {"recommendation", "transcript"}
    assert rec["explanation"]["transcript_failed_version"] == rec_service.TRANSCRIPT_REQUEST_VERSION


# ---------------------------------------------------------------------
# 3. A stored forecast still holding the template: upgraded by the page
# ---------------------------------------------------------------------

@pytest.fixture
def all_template(app, monkeypatch):
    """A plan whose stored forecast is the template throughout -- the
    recommendation AND the transcript -- made with the LLM off."""
    from app.services.forecasting_service import generate_forecast_for_profile

    with app.app_context():
        monkeypatch.setenv("USE_LLM_RECOMMENDATIONS", "false")
        row = generate_forecast_for_profile(_new_plan(app))
        monkeypatch.delenv("USE_LLM_RECOMMENDATIONS", raising=False)
        assert rec_service.ai_text_pending(rec_service.parse_recommendation(row.recommendation)) == \
            {"recommendation", "transcript"}
        return {"forecast_id": row.forecast_id, "sme_id": row.sme_id, "raw": row.recommendation}


def _one_call_payload(explanation=None):
    payload = llm_service._coerce_llm_payload(json.dumps({**ONE_CALL, **(
        {"explanation": explanation} if explanation else {})}))
    return {**payload, "generated_by": "llm:gemini", "model": MODEL}


TRANSCRIPT = {"text": "Gemini's transcript.", "generated_by": f"llm:gemini:{MODEL}"}


def test_the_page_upgrades_the_recommendation_and_the_transcript(app, all_template, monkeypatch):
    with app.app_context():
        _gemini_on(app, monkeypatch)
        monkeypatch.setattr(llm_service, "generate_recommendation_json", lambda c: _one_call_payload())
        monkeypatch.setattr(llm_service, "transcribe_forecast", lambda c: dict(TRANSCRIPT))
        data = _client(app, "owner@everywhere.test").post(
            f"/api/forecasts/{all_template['forecast_id']}/transcript").get_json()
        after = json.loads(db.session.get(ForecastResult, all_template["forecast_id"]).recommendation)

    before = json.loads(all_template["raw"])
    assert data["ok"] is True and data["changed"] == ["recommendation", "transcript"]
    assert "pending" not in data
    assert after["generated_by"] == "llm:gemini" and after["headline"] == ONE_CALL["headline"]
    assert after["explanation"] == TRANSCRIPT
    assert after["competitor_insight"]["generated_by"].startswith("llm:gemini")
    # Measurements are never the AI's: the payload and analysis are as read.
    assert after["forecast"] == before["forecast"]
    assert after["subcategory_analysis"] == before["subcategory_analysis"]


def test_a_recommendation_gemini_could_not_write_is_asked_for_again(app, all_template, monkeypatch):
    with app.app_context():
        _gemini_on(app, monkeypatch)
        monkeypatch.setattr(llm_service, "generate_recommendation_json", lambda c: None)
        monkeypatch.setattr(llm_service, "transcribe_forecast", lambda c: dict(TRANSCRIPT))
        data = _client(app, "owner@everywhere.test").post(
            f"/api/forecasts/{all_template['forecast_id']}/transcript").get_json()
        rec = rec_service.parse_recommendation(
            db.session.get(ForecastResult, all_template["forecast_id"]).recommendation)

    assert data["ok"] is True and data["changed"] == ["transcript"]
    assert data["pending"] == ["recommendation"] and data["retry_after"] == 120
    assert rec["explanation"]["generated_by"] == f"llm:gemini:{MODEL}"
    assert rec["explanation"]["transcript_failed_at"], "the wait is stamped"
    assert rec_service.transcript_upgrade_due(rec) is False, "...and honoured until it is over"


def test_the_pages_show_gemini_writing_and_mark_the_parts_it_repaints(app, all_template, monkeypatch):
    with app.app_context():
        _gemini_on(app, monkeypatch)
        client = _client(app, "owner@everywhere.test")
        planning = client.get(f"/planning?plan={all_template['sme_id']}").get_data(as_text=True)
        recommendations = client.get("/recommendations").get_data(as_text=True)
        home = client.get("/home").get_data(as_text=True)

    fid = all_template["forecast_id"]
    assert "Gemini is writing this plan&rsquo;s recommendation" in planning
    assert 'data-ai-wants="recommendation"' in planning
    for part in ("verdict", "insight"):
        assert f'data-ai-region="{fid}" data-ai-part="{part}"' in planning, part
    for part in ("badge", "verdict", "insight", "reasons", "innovation"):
        assert f'data-ai-region="{fid}" data-ai-part="{part}"' in recommendations, part
    assert f'data-ai-region="{fid}" data-ai-part="summary"' in home
    assert f"/api/forecasts/{fid}/transcript" in home, "Home queues it in the background"


def test_a_gemini_written_plan_says_so_and_asks_for_nothing(app, all_template, monkeypatch):
    with app.app_context():
        _gemini_on(app, monkeypatch)
        row = db.session.get(ForecastResult, all_template["forecast_id"])
        payload = json.loads(row.recommendation)
        payload.update(generated_by="llm:gemini", explanation=dict(TRANSCRIPT))
        row.recommendation = json.dumps(payload)
        db.session.commit()
        planning = _client(app, "owner@everywhere.test").get(
            f"/planning?plan={all_template['sme_id']}").get_data(as_text=True)
    assert "Written by Gemini" in planning
    assert "data-forecast-transcript" not in planning


# ---------------------------------------------------------------------
# 4. The competitor insight and the innovation read
# ---------------------------------------------------------------------

def _insight_context():
    return {"subcategory_analysis": None, "competitor_count": 7, "industry_type": "Food and Beverage",
            "location": "Tibag", "forecast": None}


def test_one_invented_sentence_does_not_cost_the_whole_insight():
    rule = rec_service.competitor_insight_from(None, 7, "Food and Beverage", "Tibag", None)
    llm = {"short": "7 food businesses trade here. Most earn ₱90,000 a day.",
           "detail": "There are 7 of them in Tibag. A clear niche wins. Sadly 90% of them close within a year."}
    chosen = rec_service._choose_competitor_insight(llm, "llm:gemini:x", rule, _insight_context())
    assert chosen["generated_by"] == "llm:gemini:x"
    assert chosen["short"] == "7 food businesses trade here."
    assert chosen["detail"] == "There are 7 of them in Tibag. A clear niche wins."


def test_a_plan_with_no_idea_gets_gemini_s_suggestions_unrated():
    assert llm_service._coerce_innovation({"summary": "Stand out.", "suggestions": ["a"]}) == \
        {"novelty": None, "summary": "Stand out.", "suggestions": ["a"]}
    assert llm_service._coerce_innovation({"novelty": "Huge", "summary": "x"}) is None
    assert llm_service._coerce_innovation({"suggestions": ["a"]}) is None


def test_the_prompt_asks_for_suggestions_when_there_is_no_idea(app):
    context = {"subcategory_label": None, "subcategory": None, "product_offering": "", "offering_items": [],
               "subcategory_analysis": None, "innovation_idea": "", "industry_type": "Retail",
               "location": "Tibag"}
    with app.app_context():
        prompt = llm_service._plan_detail_prompt(context)
    assert "has not said yet what makes the business different" in prompt
    assert '"innovation"' in prompt and '"suggestions"' in prompt


# ---------------------------------------------------------------------
# 5. The page script
# ---------------------------------------------------------------------

def test_the_script_repaints_and_asks_again_by_itself():
    with open(os.path.join(ROOT, "app", "static", "js", "forecast_transcript.js"), encoding="utf-8") as f:
        script = f.read()
    assert "new DOMParser().parseFromString" in script and "data-ai-region" in script
    assert "region.replaceWith(document.importNode(replacement, true))" in script
    assert re.search(r"const MAX_ROUNDS = \d+;", script)
    assert "data.retry_after" in script and "window.setTimeout" in script
    assert "innerHTML" not in script.split("function showTranscript", 1)[1].split("function successMessage", 1)[0] \
        .replace("template.innerHTML", ""), "model text is never parsed as HTML"
